<?php

/**
 * Contenu du blog — pôles 0..4 alignés sur poles_landing / méga-menu.
 */
return [
    'meta_title'       => 'Blog — performance structurée, conformité & digital | Complianz',
    'meta_description' => 'Articles, guides et retours d’expérience sur l’audit, la conformité, le développement, la performance digitale, le support et l’IA en entreprise.',

    'poles' => [
        [
            'id'        => 0,
            'slug'      => 'audit-conformite',
            'path'      => '/audit-conformite',
            'name'      => 'Conseil & Audit',
            'short'     => 'Audit',
            'hero'      => 'blue',
        ],
        [
            'id'        => 1,
            'slug'      => 'solutions-developpement',
            'path'      => '/solutions-developpement',
            'name'      => 'Développement',
            'short'     => 'Dev',
            'hero'      => 'green',
        ],
        [
            'id'        => 2,
            'slug'      => 'performance-digitale',
            'path'      => '/performance-digitale',
            'name'      => 'Performance digitale',
            'short'     => 'Performance',
            'hero'      => 'beige',
        ],
        [
            'id'        => 3,
            'slug'      => 'support-maintenance',
            'path'      => '/support-maintenance',
            'name'      => 'Support & Maintenance',
            'short'     => 'Support',
            'hero'      => 'soft',
        ],
        [
            'id'        => 4,
            'slug'      => 'intelligence-artificielle',
            'path'      => '/intelligence-artificielle',
            'name'      => 'Intelligence artificielle',
            'short'     => 'IA',
            'hero'      => 'ia',
        ],
    ],

    'articles' => [
        [
            'slug'         => 'audit-entreprise-guide-complet-2024',
            'title'        => 'Audit d’entreprise : le guide complet pour structurer et optimiser votre organisation en 2024',
            'excerpt'      => 'Méthode, périmètre, livrables et indicateurs : comment transformer un audit en plan d’action priorisé plutôt qu’en rapport qui dort dans un tiroir.',
            'body'         => <<<'MD'
<p>Un audit d’entreprise n’a de valeur que s’il débouche sur des décisions. Commencez par cadrer l’objectif (conformité, performance, risques) et le périmètre (processus, systèmes, organisation).</p>
<p>Les entretiens croisés et l’analyse documentaire permettent de repérer les écarts entre le réel et la politique affichée. Les recommandations doivent être ordonnées par criticité, effort et dépendances.</p>
<p>Enfin, un suivi à 30 / 90 jours avec des indicateurs simples évite la dérive : ce qui n’est pas mesuré ne peut pas être amélioré durablement.</p>
MD
            ,
            'date'         => '2024-01-15',
            'read_min'     => 12,
            'pole'         => 0,
            'featured'     => true,
            'author'       => ['name' => 'Pierre Matifas', 'initials' => 'PM'],
            'image'        => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=960&q=80',
            'image_alt'    => 'Équipe en réunion de travail avec ordinateurs portables',
        ],
        [
            'slug'         => 'registre-traitements-rgpd-mise-a-jour',
            'title'        => 'Registre des traitements : la mise à jour qui protège vraiment votre DPO',
            'excerpt'      => 'Les pièges fréquents (sous-déclaration, bases légales floues) et une trame de revue trimestrielle adaptée aux PME.',
            'body'         => '<p>Le registre n’est pas une archive : c’est l’outil qui relie les traitements aux finalités et aux mesures de sécurité. Une revue régulière avec les métiers évite les surprises lors d’un contrôle.</p>',
            'date'         => '2024-01-10',
            'read_min'     => 8,
            'pole'         => 0,
            'featured'     => false,
            'author'       => ['name' => 'Claire Renaud', 'initials' => 'CR'],
            'image'        => null,
            'image_alt'    => '',
        ],
        [
            'slug'         => 'erp-crm-comment-eviter-projet-bloque',
            'title'        => 'ERP / CRM : comment éviter le projet bloqué à mi-parcours',
            'excerpt'      => 'Cadrage des données, rôles utilisateurs et intégrations : trois leviers pour débloquer un SI qui peine à vivre en production.',
            'body'         => '<p>Un ERP réussit quand les processus sont clarifiés avant la configuration. Nommez un sponsor métier, figez un périmètre V1 réaliste et planifiez des itérations plutôt qu’un big bang.</p>',
            'date'         => '2024-01-08',
            'read_min'     => 10,
            'pole'         => 1,
            'featured'     => false,
            'author'       => ['name' => 'Marc Delmas', 'initials' => 'MD'],
            'image'        => null,
            'image_alt'    => '',
        ],
        [
            'slug'         => 'apis-internes-securiser-echanges-si',
            'title'        => 'APIs internes : sécuriser les échanges sans ralentir les équipes',
            'excerpt'      => 'Authentification, journalisation et environnements de test : un socle minimal pour les intégrations entre SaaS et outils métiers.',
            'body'         => '<p>Les APIs exposées en interne méritent les mêmes principes qu’en externe : secrets hors du code, limitation de débit, traçabilité des appels et révocation des jetons.</p>',
            'date'         => '2024-01-05',
            'read_min'     => 7,
            'pole'         => 1,
            'featured'     => false,
            'author'       => ['name' => 'Marc Delmas', 'initials' => 'MD'],
            'image'        => null,
            'image_alt'    => '',
        ],
        [
            'slug'         => 'seo-technique-checklist-2024',
            'title'        => 'SEO technique : la checklist qui évite 80 % des erreurs classiques',
            'excerpt'      => 'Indexation, Core Web Vitals, données structurées : où regarder en premier quand le trafic stagne malgré un contenu solide.',
            'body'         => '<p>Avant d’écrire davantage, vérifiez que les pages utiles sont bien explorées, que les canoniques sont cohérentes et que les temps de chargement ne pénalisent pas la mobile-first.</p>',
            'date'         => '2024-01-03',
            'read_min'     => 9,
            'pole'         => 2,
            'featured'     => false,
            'author'       => ['name' => 'Lina Okafor', 'initials' => 'LO'],
            'image'        => null,
            'image_alt'    => '',
        ],
        [
            'slug'         => 'tunnel-vente-b2b-mesurer-conversion',
            'title'        => 'Tunnel de vente B2B : mesurer la conversion sans noyer la direction dans des KPIs',
            'excerpt'      => 'Du clic au rendez-vous qualifié : quelques indicateurs suffisent si le CRM est la source de vérité.',
            'body'         => '<p>Alignez marketing et ventes sur une définition commune du lead qualifié, puis reliez les campagnes aux opportunités pour calculer un coût par rendez-vous réel, pas théorique.</p>',
            'date'         => '2023-12-28',
            'read_min'     => 6,
            'pole'         => 2,
            'featured'     => false,
            'author'       => ['name' => 'Lina Okafor', 'initials' => 'LO'],
            'image'        => null,
            'image_alt'    => '',
        ],
        [
            'slug'         => 'infogerance-pme-sla-realistes',
            'title'        => 'Infogérance PME : fixer des SLA réalistes avec votre prestataire',
            'excerpt'      => 'Heures ouvrées, criticité des applicatifs et communication d’incident : le cadre minimal pour dormir tranquille.',
            'body'         => '<p>Classez vos services par impact métier, définissez des délais de prise en charge distincts des délais de résolution, et exigez un compte-rendu post-incident pour les incidents majeurs.</p>',
            'date'         => '2023-12-22',
            'read_min'     => 5,
            'pole'         => 3,
            'featured'     => false,
            'author'       => ['name' => 'Thomas Weber', 'initials' => 'TW'],
            'image'        => null,
            'image_alt'    => '',
        ],
        [
            'slug'         => 'sauvegardes-restaurations-tests-reguliers',
            'title'        => 'Sauvegardes : pourquoi vos restaurations méritent le même calendrier que les backups',
            'excerpt'      => 'Un backup non testé est une promesse. Voici comment industrialiser des tests de restauration sans bloquer la production.',
            'body'         => '<p>Automatisez des restaurations partielles sur un environnement isolé, vérifiez l’intégrité des fichiers et documentez le temps de récupération réel — c’est lui qui compte en crise.</p>',
            'date'         => '2023-12-18',
            'read_min'     => 6,
            'pole'         => 3,
            'featured'     => false,
            'author'       => ['name' => 'Thomas Weber', 'initials' => 'TW'],
            'image'        => null,
            'image_alt'    => '',
        ],
        [
            'slug'         => 'ia-generative-donnees-sensibles-entreprise',
            'title'        => 'IA générative et données sensibles : cadre minimal pour les équipes',
            'excerpt'      => 'Shadow IT, prompts et rétention : comment encadrer les usages sans brider l’innovation.',
            'body'         => '<p>Fixez des listes de données interdites dans les prompts, privilégiez les offres entreprise avec options de non-rétention et tracez les cas d’usage par direction pour ajuster la formation.</p>',
            'date'         => '2023-12-12',
            'read_min'     => 11,
            'pole'         => 4,
            'featured'     => false,
            'author'       => ['name' => 'Amélie Forest', 'initials' => 'AF'],
            'image'        => null,
            'image_alt'    => '',
        ],
        [
            'slug'         => 'agents-ia-process-metiers-pilotage',
            'title'        => 'Agents IA sur processus métiers : du prototype au pilotage',
            'excerpt'      => 'Garde-fous, reprise sur erreur et indicateurs de qualité pour passer en production sans effet démo.',
            'body'         => '<p>Commencez par un périmètre étroit avec file d’attente humaine, mesurez les taux de succès par intention et planifiez des seuils d’escalade explicites vers un opérateur.</p>',
            'date'         => '2023-12-05',
            'read_min'     => 9,
            'pole'         => 4,
            'featured'     => false,
            'author'       => ['name' => 'Amélie Forest', 'initials' => 'AF'],
            'image'        => null,
            'image_alt'    => '',
        ],
        [
            'slug'         => 'iso-27001-premiers-pas-pme',
            'title'        => 'ISO 27001 : premiers pas pour une PME sans dédoubler le SI',
            'excerpt'      => 'Le socle politique de sécurité, la cartographie des actifs et la priorisation des mesures : une entrée en matière pragmatique.',
            'body'         => '<p>Ne vis pas la certification au jour un : construisez un SMSI minimal viable avec les risques réels, puis enrichissez les preuves au fil des audits internes.</p>',
            'date'         => '2023-11-28',
            'read_min'     => 10,
            'pole'         => 0,
            'featured'     => false,
            'author'       => ['name' => 'Claire Renaud', 'initials' => 'CR'],
            'image'        => null,
            'image_alt'    => '',
        ],
        [
            'slug'         => 'cro-reunion-design-tests-ab',
            'title'        => 'CRO : quand la réunion design vaut plus qu’un nouvel outil d’A/B testing',
            'excerpt'      => 'Alignement sur l’objectif de page et hiérarchie de l’information avant de multiplier les variantes.',
            'body'         => '<p>Un test A/B utile part d’une hypothèse claire et d’un volume suffisant. Souvent, clarifier la proposition de valeur et réduire les frictions du formulaire bat cinq micro-tests cosmétiques.</p>',
            'date'         => '2023-11-20',
            'read_min'     => 5,
            'pole'         => 2,
            'featured'     => false,
            'author'       => ['name' => 'Lina Okafor', 'initials' => 'LO'],
            'image'        => null,
            'image_alt'    => '',
        ],
    ],
];
