<?php

/**
 * Offres « Nos packs » du méga menu — une entrée par slug URL (/nos-packs/{slug}).
 */
return [
    'pack-diagnostic-vision' => [
        'title'            => 'Pack Diagnostic & Vision',
        'pole'             => 0,
        'pole_name'        => 'Conseil, Audit & Conformité',
        'pole_url'         => '/audit-conformite',
        'category'         => 'Conseil / Audit / Structuration',
        'meta_title'       => 'Pack Diagnostic & Vision — audit express & feuille de route | Complianz',
        'meta_description' => 'Analyse globale de l’entreprise : blocages, risques, priorités stratégiques. Tarif indicatif 3 000–7 000 €. Restitution et plan d’action priorisé.',
        'price'            => '3 000–7 000 €',
        'tagline'          => 'Vous identifiez précisément où vous perdez du temps et de l\'argent avant d\'investir.',
        'pour_qui'         => 'PME désorganisée ou avant un gros investissement',
        'signature'        => false,
        'objective'        => 'Vous identifiez précisément où vous perdez du temps et de l\'argent avant d\'investir.',
        'intro'            => 'Analyse globale de l’entreprise permettant d’identifier les blocages, les risques, les axes d’amélioration et les priorités stratégiques.',
        'value_headline'   => 'Une analyse globale pour identifier les blocages et définir les priorités stratégiques — avant d’engager des budgets dans le mauvais ordre.',
        'benefits'         => [
            'Vision claire de l’entreprise et de ses enjeux transverses.',
            'Identification des problèmes réels (et pas seulement des symptômes).',
            'Priorisation des actions et arbitrages pour la direction.',
            'Réduction des erreurs stratégiques et des investissements inutiles.',
            'Base de travail solide pour la suite : conformité, SI et performance.',
        ],
        'characteristics'  => [
            'Durée : 2 à 4 semaines selon périmètre et disponibilité.',
            '2 à 4 sessions d’échange avec le dirigeant (et parties prenantes clés).',
            'Analyse documentaire ciblée + entretiens structurés.',
            'Restitution complète : rapport synthétique et présentation (visio ou présentiel).',
            'Plan d’action priorisé avec niveaux d’effort et jalons.',
            'Support à la prise en main : 15 jours après restitution pour clarifications ciblées.',
        ],
        'client_summary'   => 'Vous comprenez enfin ce qui bloque votre entreprise et savez exactement quoi faire pour avancer.',
        'hero_checklist'   => [
            'Audit global & vision transverse',
            'Audit de conformité (niveau adapté)',
            'Analyse organisationnelle',
            'Analyse outils & processus',
            'Restitution exécutive complète',
            'Plan d’action priorisé',
        ],
        'content_blocks'   => [
            [
                'title'      => 'Audit global d’entreprise',
                'bullets'    => [
                    'Photographie des enjeux : organisation, SI, données et risques sur un périmètre défini avec vous.',
                    'Entretiens ciblés et croisement des sources pour objectiver les constats.',
                ],
                'url'        => '/audit-conformite/audit-conseil/audit-organisationnel',
                'link_label' => 'Audit organisationnel',
            ],
            [
                'title'      => 'Audit de conformité (niveau adapté)',
                'bullets'    => [
                    'Revues RGPD / référentiels selon votre maturité (pas de sur-audit inutile).',
                    'Identification des écarts prioritaires et des preuves à constituer.',
                ],
                'url'        => '/audit-conformite/conformite-rgpd/audit-rgpd',
                'link_label' => 'Audit RGPD',
            ],
            [
                'title'      => 'Analyse organisationnelle',
                'bullets'    => [
                    'Cartographie des rôles, flux et points de friction entre métiers.',
                    'Alignement avec votre capacité réelle à exécuter (charge, compétences, gouvernance).',
                ],
                'url'        => '/audit-conformite/audit-conseil/audit-organisationnel',
                'link_label' => 'Structuration & diagnostic',
            ],
            [
                'title'      => 'Analyse outils & processus',
                'bullets'    => [
                    'Revue des usages réels (ERP, CRM, bureautique, tickets…) vs besoins métier.',
                    'Détection des ressaisies, absences d’interface et dettes opérationnelles.',
                ],
                'url'        => '/solutions-developpement/erp-crm',
                'link_label' => 'ERP / CRM & outils métiers',
            ],
            [
                'title'      => 'Restitution complète',
                'bullets'    => [
                    'Synthèse direction + dossier de constats structuré (exploitable, pas encyclopédique).',
                    'Supports pour aligner COMEX et sponsors sur les priorités.',
                ],
                'url'        => '/audit-conformite/audit-conseil/conseil-strategique',
                'link_label' => 'Conseil stratégique',
            ],
            [
                'title'      => 'Plan d’action priorisé',
                'bullets'    => [
                    'Roadmap ordonnée (quick wins / chantiers structurants) avec ordres de grandeur.',
                    'Critères de décision pour savoir quoi lancer, quand, et avec quels prérequis.',
                ],
                'url'        => '/audit-conformite/audit-conseil/conseil-strategique',
                'link_label' => 'Feuille de route & arbitrages',
            ],
        ],
        'ideal_for'        => [
            'Dirigeants de TPE/PME qui veulent une vision partagée avant des investissements lourds.',
            'Structures en croissance ou en cadrage ISO, RGPD ou levée de fonds.',
            'Organisations avec des zones floues entre métiers, SI et conformité.',
        ],
        'deliverables'     => [
            'Ateliers de cadrage avec les parties prenantes clés.',
            'Cartographie synthétique des risques et opportunités (quick wins inclus).',
            'Feuille de route priorisée (horizon 6–18 mois) et jalons de pilotage.',
            'Synthèse exécutive pour la direction et supports de communication interne.',
        ],
        'duration'         => '2 à 4 semaines selon périmètre et disponibilité des équipes.',
        'phases'           => [
            ['title' => 'Cadrage & collecte', 'text' => 'Entretiens, revue documentaire ciblée et définition du périmètre audité (métiers, SI, données).'],
            ['title' => 'Diagnostic & analyse', 'text' => 'Croisement des constats : organisation, conformité, outils ; identification des leviers et des risques.'],
            ['title' => 'Restitution & plan d’action', 'text' => 'Présentation des conclusions, arbitrages proposés et plan priorisé avec niveaux d’effort et prochaines étapes.'],
        ],
        'related'          => [
            ['label' => 'Audit organisationnel', 'url' => '/audit-conformite/audit-conseil/audit-organisationnel'],
            ['label' => 'Audit RGPD', 'url' => '/audit-conformite/conformite-rgpd/audit-rgpd'],
            ['label' => 'Cybersécurité', 'url' => '/audit-conformite/cybersecurite'],
            ['label' => 'Conseil stratégique', 'url' => '/audit-conformite/audit-conseil/conseil-strategique'],
        ],
        'faq'              => [
            ['q' => 'Le diagnostic remplace-t-il un audit de certification ?', 'a' => 'Non : il vise la clarté décisionnelle et la priorisation. Les audits réglementaires ou certification restent des prestations distinctes que nous pouvons enchaîner ensuite.'],
            ['q' => 'Peut-on limiter le périmètre à un site ou une filiale ?', 'a' => 'Oui. Le périmètre est défini en amont (entité, périmètre SI, traitements concernés) pour maîtriser coût et délais.'],
            ['q' => 'Quels livrables recevons-nous concrètement ?', 'a' => 'Une synthèse direction, un dossier de constats structuré et une roadmap chiffrée en ordre de priorité — sans noyer les équipes dans des documents inutilisables.'],
        ],
    ],

    'pack-mise-en-conformite-securisation' => [
        'title'            => 'Pack Mise en conformité & sécurisation',
        'pole'             => 0,
        'pole_name'        => 'Conseil, Audit & Conformité',
        'pole_url'         => '/audit-conformite',
        'meta_title'       => 'Pack Mise en conformité RGPD / ISO & sécurisation | Complianz',
        'meta_description' => 'Passer des constats aux registres, politiques et mesures techniques proportionnées. RGPD, ISO 27001 ou SMSI : un chemin structuré. Indicatif 8 000–20 000 €.',
        'price'            => '8 000–20 000 €',
        'tagline'          => 'Vous devenez conforme sans alourdir votre organisation au quotidien.',
        'pour_qui'         => 'Structure réglementée ou sous contrainte ISO / RGPD',
        'signature'        => false,
        'intro'            => 'Nous transformons les obligations (RGPD, référentiels ISO, politique de sécurité) en dispositifs opérationnels : documentation, gouvernance, sensibilisation courte et points de contrôle.',
        'ideal_for'        => [
            'Structures qui ont besoin de « passer le cap » réglementaire sans internaliser une équipe dédiée.',
            'Projets suite à un audit, une mise en demeure ou une exigence client / appel d\'offres.',
            'Organisations multi-sites qui doivent harmoniser les pratiques.',
        ],
        'deliverables'     => [
            'Mise à jour ou création des documents réglementaires clés (registre, DPIA si nécessaire, politiques).',
            'Plan de mise en œuvre des mesures organisationnelles et techniques proportionnées.',
            'Modèles de procédures et matrices de responsabilités.',
            'Support à la preuve : indicateurs, jalons et préparation aux contrôles.',
        ],
        'duration'         => '2 à 5 mois en général, selon volumétrie et maturité.',
        'phases'           => [
            ['title' => 'État des lieux & écart', 'text' => 'Alignement sur le référentiel visé et identification des écarts bloquants.'],
            ['title' => 'Conception & rédaction', 'text' => 'Production des livrables, validation métier et arbitrages sécurité / UX.'],
            ['title' => 'Déploiement & capitalisation', 'text' => 'Mise en circulation des documents, formation ciblée et premier cycle d\'amélioration.'],
        ],
        'related'          => [
            ['label' => 'Mise en conformité RGPD', 'url' => '/audit-conformite/conformite-rgpd'],
            ['label' => 'ISO 27001', 'url' => '/audit-conformite/certifications-iso/iso-27001'],
            ['label' => 'Politique de sécurité', 'url' => '/audit-conformite/cybersecurite/politique-securite'],
            ['label' => 'DPO externalisé', 'url' => '/audit-conformite/conformite-rgpd/dpo-externalise'],
        ],
        'faq'              => [
            ['q' => 'Peut-on cibler uniquement le RGPD ou uniquement l\'ISO 27001 ?', 'a' => 'Oui. Le pack est calibré sur votre référentiel prioritaire ; les synergies RGPD / sécurité sont exploitées quand c\'est pertinent pour éviter les doublons.'],
            ['q' => 'Qui valide les documents côté client ?', 'a' => 'Un sponsor métier et un référent SI ou juridique selon les sujets. Nous facilitons les arbitrages pour éviter les allers-retours infinis.'],
            ['q' => 'Inclut-il des prestations techniques sur site ?', 'a' => 'Les mesures techniques sont décrites et peuvent être réalisées par vos équipes ou nos partenaires ; nous coordonnons et vérifions la cohérence avec les exigences.'],
        ],
    ],

    'pack-structuration-organisation' => [
        'title'            => 'Pack Structuration & Organisation',
        'pole'             => 0,
        'pole_name'        => 'Conseil, Audit & Conformité',
        'pole_url'         => '/audit-conformite',
        'meta_title'       => 'Pack Structuration & organisation — gouvernance & processus | Complianz',
        'meta_description' => 'Clarifiez rôles, processus et pilotage : schéma de gouvernance, référentiels et indicateurs alignés sur la stratégie. Indicatif 10 000–30 000 €.',
        'price'            => '10 000–30 000 €',
        'tagline'          => 'Vous clarifiez rôles et flux — moins de silos, des décisions qui avancent.',
        'pour_qui'         => 'Entreprise en croissance ou multi-sites',
        'signature'        => false,
        'intro'            => 'Au-delà de la conformité ponctuelle, ce pack installe une organisation qui tient dans la durée : cartographie des flux, règles de gestion, interfaces entre métiers et SI, et indicateurs utiles au COMEX.',
        'ideal_for'        => [
            'Entreprises en réorganisation post-fusion ou forte croissance.',
            'Directions générales qui veulent débloquer les silos et accélérer la décision.',
            'Structures préparant certification qualité ou passage à l\'échelle.',
        ],
        'deliverables'     => [
            'Cartographie des processus et points de friction.',
            'Schéma de gouvernance et matrice RACI / responsabilités.',
            'Référentiel de processus prioritaires (version exploitable par les équipes).',
            'Indicateurs et rituels de pilotage (fréquence, audiences, outils).',
        ],
        'duration'         => '3 à 6 mois selon nombre de sites et complexité métiers.',
        'phases'           => [
            ['title' => 'Immersion & diagnostic organisationnel', 'text' => 'Entretiens, observation des flux réels et alignement sur la stratégie.'],
            ['title' => 'Modèle cible & arbitrages', 'text' => 'Scénarios, impacts RH et SI, priorisation par valeur et risque.'],
            ['title' => 'Déploiement raisonné', 'text' => 'Plans de transition, communication interne et mesure de l\'adhésion.'],
        ],
        'related'          => [
            ['label' => 'Structuration & gouvernance', 'url' => '/audit-conformite/audit-conseil/structuration-gouvernance'],
            ['label' => 'ISO 9001', 'url' => '/audit-conformite/certifications-iso/iso-9001'],
            ['label' => 'Création d\'entreprise', 'url' => '/audit-conformite/audit-conseil/creation-entreprise'],
            ['label' => 'Stratégie RSE', 'url' => '/audit-conformite/rse/strategie-rse'],
        ],
        'faq'              => [
            ['q' => 'Différence avec un simple audit ?', 'a' => 'L\'audit constate ; ce pack produit un modèle cible et des changements organisés dans le temps, avec des garde-fous pour ne pas « figer » l\'entreprise.'],
            ['q' => 'Comment gérez-vous la charge pour les équipes ?', 'a' => 'Nous planifions des ateliers courts, des livrables progressifs et des arbitrages à date fixe pour éviter la fatigue de projet.'],
            ['q' => 'Peut-on couvrir plusieurs pays ou BU ?', 'a' => 'Oui : nous adaptons le niveau de granularité (groupe / pays / site) et harmonisons les référentiels tout en laissant de la marge locale réglementaire.'],
        ],
    ],

    'pack-structuration-performance-globale' => [
        'title'            => 'Pack Structuration & Performance globale',
        'pole'             => 0,
        'pole_name'        => 'Conseil, Audit & Conformité',
        'pole_url'         => '/audit-conformite',
        'meta_title'       => 'Pack Structuration & performance globale — transformation ★ | Complianz',
        'meta_description' => 'Offre signature : alignement stratégique, conformité, organisation et pilotage de la performance dans une trajectoire coordonnée. Indicatif 20 000–50 000 €+.',
        'price'            => '20 000–50 000 €+',
        'tagline'          => 'Vous pilotez conformité, SI et organisation avec une trajectoire unique et mesurable.',
        'pour_qui'         => 'ETI / transformation multi-enjeux (M&A, international, certification)',
        'signature'        => true,
        'intro'            => 'Pour les dirigeants qui veulent une dynamique unique : diagnostic partagé, plan maître RSE / conformité / organisation / SI, et pilotage jusqu\'aux résultats mesurables.',
        'ideal_for'        => [
            'Groupes ou ETI à la transformation multiple (M&A, internationalisation, certification).',
            'Organisations où les projets « tombent » entre les sièges métiers.',
            'Vision long terme avec exigence forte des parties prenantes externes.',
        ],
        'deliverables'     => [
            'Plan maître et gouvernance de programme multi-volets.',
            'Feuilles de route synchronisées métiers / conformité / SI.',
            'Instances de pilotage, reporting consolidé et indicateurs de valeur.',
            'Accompagnement change management ciblé sur les populations critiques.',
        ],
        'duration'         => '6 à 18 mois selon ambition et périmètre géographique.',
        'phases'           => [
            ['title' => 'Vision & cadrage global', 'text' => 'Alignement COMEX, analyse des interdépendances et arbitrages initiaux.'],
            ['title' => 'Ingénierie & déploiement par vagues', 'text' => 'Mise en œuvre coordonnée avec jalons, budgets et gestion des risques de projet.'],
            ['title' => 'Consolidation & autonomie', 'text' => 'Transmission des méthodes, optimisation continue et préparation à l\'internalisation.'],
        ],
        'related'          => [
            ['label' => 'Audit global & Conseil', 'url' => '/audit-conformite/audit-conseil'],
            ['label' => 'Certifications ISO', 'url' => '/audit-conformite/certifications-iso'],
            ['label' => 'Démarche RSE', 'url' => '/audit-conformite/rse'],
            ['label' => 'Cybersécurité', 'url' => '/audit-conformite/cybersecurite'],
        ],
        'faq'              => [
            ['q' => 'Pourquoi une fourchette tarifaire aussi large ?', 'a' => 'Le périmètre couvre souvent plusieurs pays, filiales ou référentiels ; nous figeons un périmètre MVP puis des extensions par vagues pour maîtriser le budget.'],
            ['q' => 'Comment s\'articule avec vos équipes internes ?', 'a' => 'Nous pouvons co-piloter avec un PMO interne ou prendre le lead selon votre maturité ; les rôles sont formalisés dès le cadrage.'],
            ['q' => 'Inclut-il du développement logiciel ?', 'a' => 'Le pack est orienté organisation et conformité ; les développements significatifs sont traités via les offres Solutions & Développement en orchestration avec ce programme.'],
        ],
    ],

    'pack-direction-strategique-externalisee' => [
        'title'            => 'Pack Direction stratégique externalisée',
        'pole'             => 0,
        'pole_name'        => 'Conseil, Audit & Conformité',
        'pole_url'         => '/audit-conformite',
        'meta_title'       => 'Direction stratégique externalisée — COMEX à temps partagé | Complianz',
        'meta_description' => 'Un senior disponible en récurrence pour arbitrer la stratégie, la conformité et les grands projets. Formule récurrente indicative 1 000–3 000 €/mois.',
        'price'            => '1 000–3 000 €/mois',
        'tagline'          => 'Vous décidez avec des arbitrages préparés et des priorités qui tiennent dans le temps.',
        'pour_qui'         => 'Dirigeant sans COMEX dédoublé ou en transition',
        'signature'        => false,
        'intro'            => 'Une présence régulière (mensuelle ou bi-hebdomadaire) pour tenir le cap : préparation de COMEX, arbitrages structurants, liaison avec vos experts internes et externes.',
        'ideal_for'        => [
            'Dirigeants de PME / ETI sans direction générale dédoublée.',
            'Transitions (nouveau DG, intégration, levée de fonds).',
            'Projets transverses où il manque un « fil rouge » décisionnel.',
        ],
        'deliverables'     => [
            'Rituels de pilotage (cadence, ordre du jour, suivi des décisions).',
            'Supports de priorisation et communication COMEX.',
            'Veille ciblée réglementaire / sectorielle selon vos risques.',
            'Mise en relation avec les bonnes expertises du groupe Complianz.',
        ],
        'duration'         => 'Engagement minimum 3 mois ; renouvellement au trimestre ou à l\'année.',
        'phases'           => [
            ['title' => 'Onboarding & diagnostic flash', 'text' => 'Compréhension du contexte, des parties prenantes et des sujets sensibles.'],
            ['title' => 'Rythme de pilotage', 'text' => 'Installation des instances, indicateurs légers et boucles de décision courtes.'],
            ['title' => 'Optimisation & transfert', 'text' => 'Montée en autonomie des équipes et ajustement du périmètre d\'intervention.'],
        ],
        'related'          => [
            ['label' => 'Conseil stratégique', 'url' => '/audit-conformite/audit-conseil/conseil-strategique'],
            ['label' => 'Structuration & gouvernance', 'url' => '/audit-conformite/audit-conseil/structuration-gouvernance'],
            ['label' => 'Pilotage commercial', 'url' => '/performance-digitale/pilotage-commercial'],
            ['label' => 'Stratégie digitale', 'url' => '/performance-digitale/strategie-digitale'],
        ],
        'faq'              => [
            ['q' => 'Est-ce du coaching de dirigeant ?', 'a' => 'Non prioritairement : nous apportons une expertise métier et transverse (stratégie, conformité, SI) avec des livrables et des arbitrages — le coaching pur peut compléter si besoin.'],
            ['q' => 'Quelle disponibilité ?', 'a' => 'Typiquement une à deux sessions par mois + pointeurs asynchrones ; les formules intensives existent en phase de crise ou de closing.'],
            ['q' => 'Confidentialité et conflits d\'intérêts ?', 'a' => 'Convention de confidentialité, déclaration de conflits et périmètre d\'intervention formalisés avant démarrage.'],
        ],
    ],

    'pack-presence-digitale-outil-base' => [
        'title'            => 'Pack Présence digitale & outil de base',
        'pole'             => 1,
        'pole_name'        => 'Solutions & Développement',
        'pole_url'         => '/solutions-developpement',
        'meta_title'       => 'Pack présence web & outil de base — vitrine, CRM léger | Complianz',
        'meta_description' => 'Site vitrine ou e-commerce léger, messagerie pro, socle CRM ou ticketing selon besoin. Fondations digitales propres. Indicatif 5 000–12 000 €.',
        'price'            => '5 000–12 000 €',
        'tagline'          => 'Vous obtenez une présence web crédible et des demandes mieux qualifiées, vite.',
        'pour_qui'         => 'PME qui professionnalise sa présence ou refonte d’image',
        'signature'        => false,
        'intro'            => 'Un socle web crédible, rapide à administrer, relié à vos processus commerciaux ou support essentiels — sans projet ERP interminable.',
        'ideal_for'        => [
            'PME qui sortent d\'une phase artisanale ou qui refondent leur image.',
            'Structures avec peu de ressources techniques internes.',
            'Besoin de déployer vite une vitrine + un canal de demande qualifié.',
        ],
        'deliverables'     => [
            'Site vitrine ou boutique simple (stack adaptée à votre maintenance).',
            'Formulaires et tracking des demandes (RGPD-friendly).',
            'Connexion à un outil de pilotage léger (CRM, helpdesk ou tableur maîtrisé).',
            'Documentation courte pour vos équipes et hébergement cadré.',
        ],
        'duration'         => '4 à 10 semaines selon contenus et validations.',
        'phases'           => [
            ['title' => 'Spécifications & UX', 'text' => 'Atelier besoins, arborescence, maquettes rapides et validation éditoriale.'],
            ['title' => 'Construction & contenus', 'text' => 'Intégration, SEO technique de base, mise en ligne progressive.'],
            ['title' => 'Recette & transfert', 'text' => 'Tests, formation courte et passage des accès / procédures.'],
        ],
        'related'          => [
            ['label' => 'Site vitrine', 'url' => '/solutions-developpement/creation-site-web/site-vitrine'],
            ['label' => 'Landing pages', 'url' => '/solutions-developpement/creation-site-web/landing-pages'],
            ['label' => 'WordPress & CMS', 'url' => '/solutions-developpement/creation-site-web/wordpress-cms'],
            ['label' => 'CRM sur mesure', 'url' => '/solutions-developpement/erp-crm/crm-sur-mesure'],
        ],
        'faq'              => [
            ['q' => 'WordPress ou développement sur mesure ?', 'a' => 'Nous recommandons la voie la plus simple à maintenir pour vous ; WordPress ou no-code souvent pour une vitrine, sur mesure si règles métiers fortes dès le départ.'],
            ['q' => 'L\'hébergement est-il inclus ?', 'a' => 'Nous dimensionnons et pouvons inclure l\'hébergement via nos offres Support & Maintenance ; sinon nous vous laissons une fiche prête pour votre infogéreur.'],
            ['q' => 'Peut-on ajouter du e-commerce plus tard ?', 'a' => 'Oui : nous anticipons l\'architecture (catalogue, paiement, logistique) pour limiter la refonte lorsque vous montez en gamme.'],
        ],
    ],

    'pack-structuration-outils-pilotage' => [
        'title'            => 'Pack Structuration des outils & pilotage',
        'pole'             => 1,
        'pole_name'        => 'Solutions & Développement',
        'pole_url'         => '/solutions-developpement',
        'meta_title'       => 'Pack CRM/ERP, automatisation & pilotage | Complianz',
        'meta_description' => 'Harmonisez outils métiers, flux de données et tableaux de bord : intégrations, workflows, rôles et indicateurs. Indicatif 15 000–40 000 €.',
        'price'            => '15 000–40 000 €',
        'tagline'          => 'Vous arrêtez les ressaisies : une donnée fiable pour piloter le réel.',
        'pour_qui'         => 'Équipes noyées sous les exports Excel',
        'signature'        => false,
        'intro'            => 'Quand l\'entreprise a plusieurs outils qui se marchent dessus, ce pack redessine le schéma cible : quel outil porte quelle donnée, quelles intégrations, quels workflows automatisés.',
        'ideal_for'        => [
            'Équipes commerciales / ops avec exports Excel chronophages.',
            'Déploiement CRM ou ERP partiel qui peine à être adopté.',
            'Besoin de tableaux de bord fiables pour le COMEX.',
        ],
        'deliverables'     => [
            'Cartographie applicative et matrice des flux.',
            'Paramétrage / intégrations (API, ETL léger, connecteurs).',
            'Workflows (validation, alertes, affectation).',
            'Tableaux de bord et définitions d\'indicateurs partagés.',
        ],
        'duration'         => '2 à 5 mois selon nombre d\'outils et qualité des données.',
        'phases'           => [
            ['title' => 'Audit outils & données', 'text' => 'Interviews, extraction d\'échantillons et identification des doublons / trous.'],
            ['title' => 'Architecture cible', 'text' => 'Choix de la plateforme pivot, règles de gouvernance data et plan d\'intégration.'],
            ['title' => 'Mise en production & adoption', 'text' => 'Déploiement par lots, formation ciblée et mesure d\'usage.'],
        ],
        'related'          => [
            ['label' => 'ERP / CRM', 'url' => '/solutions-developpement/erp-crm'],
            ['label' => 'Intégration Odoo', 'url' => '/solutions-developpement/erp-crm/integration-odoo'],
            ['label' => 'Automatisation & API', 'url' => '/solutions-developpement/developpement-logiciel/automatisation-api'],
            ['label' => 'Tableau de bord commercial', 'url' => '/performance-digitale/pilotage-commercial/tableau-de-bord'],
        ],
        'faq'              => [
            ['q' => 'Faut-il changer d\'ERP ?', 'a' => 'Pas nécessairement : nous optimisons souvent l\'existant en sécurisant les flux et les rôles avant tout big bang.'],
            ['q' => 'Qui prépare les données ?', 'a' => 'Un plan de nettoyage est co-construit ; la propriété des données reste côté client avec nos guides et scripts d\'aide.'],
            ['q' => 'Inclut-il du développement lourd ?', 'a' => 'Le pack vise intégration et paramétrage ; les briques logicielles majeures sont chiffrées à part si nécessaire.'],
        ],
    ],

    'pack-optimisation-automatisation-avancee' => [
        'title'            => 'Pack Optimisation & automatisation avancée',
        'pole'             => 1,
        'pole_name'        => 'Solutions & Développement',
        'pole_url'         => '/solutions-developpement',
        'meta_title'       => 'Pack automatisation avancée & logiciel sur mesure | Complianz',
        'meta_description' => 'Automatisez les processus à forte valeur : API, scripts, workflows métier, briques logicielles ciblées. Indicatif 20 000–60 000 €.',
        'price'            => '20 000–60 000 €',
        'tagline'          => 'Vous réduisez le travail manuel là où il coûte cher en temps et en erreurs.',
        'pour_qui'         => 'Opérations à fort volume (facturation, logistique, support)',
        'signature'        => false,
        'intro'            => 'Pour les processus mûrs mais encore trop manuels : orchestration, micro-services, connecteurs et interfaces utilisateurs minimales mais efficaces.',
        'ideal_for'        => [
            'Opérations avec volumes élevés (facturation, logistique, support).',
            'Besoin d\'un logiciel métier ciblé sans refonte ERP globale.',
            'Équipes techniques capables de maintenir avec notre documentation.',
        ],
        'deliverables'     => [
            'Cartographie des automatisations à ROI prioritaire.',
            'Développement de connecteurs / services et garde-fous de reprise sur erreur.',
            'Interfaces ou bots métier selon cas d\'usage.',
            'Supervision, logs et runbook pour les équipes IT.',
        ],
        'duration'         => '3 à 7 mois selon criticité et environnements.',
        'phases'           => [
            ['title' => 'Design d\'automatisation', 'text' => 'Cas d\'usage, risques, volumétrie et critères de succès mesurables.'],
            ['title' => 'Implémentation & tests', 'text' => 'Développement itératif, jeux d\'essai et pré-production.'],
            ['title' => 'Mise en prod & hypercare', 'text' => 'Go-live encadré, monitoring renforcé puis stabilisation.'],
        ],
        'related'          => [
            ['label' => 'Développement logiciel', 'url' => '/solutions-developpement/developpement-logiciel'],
            ['label' => 'Application métier', 'url' => '/solutions-developpement/developpement-logiciel/application-metier'],
            ['label' => 'Automatisation IA (n8n)', 'url' => '/intelligence-artificielle/automatisation-ia/automatisation-ia-avec-n8n'],
            ['label' => 'Automatisation IA', 'url' => '/intelligence-artificielle/automatisation-ia'],
        ],
        'faq'              => [
            ['q' => 'Low-code / no-code ou code pur ?', 'a' => 'Nous choisissons selon la criticité, la dette technique et vos compétences internes ; mix possible.'],
            ['q' => 'SLA et maintenance ?', 'a' => 'Les niveaux de service sont contractualisés ; la maintenance peut être prise en charge par nos offres Support & Maintenance.'],
            ['q' => 'RGPD et logs ?', 'a' => 'Les flux personnels sont inventoriés, minimisés et tracés conformément à vos registres et politiques.'],
        ],
    ],

    'pack-systeme-digital-complet' => [
        'title'            => 'Pack Système digital complet',
        'pole'             => 1,
        'pole_name'        => 'Solutions & Développement',
        'pole_url'         => '/solutions-developpement',
        'meta_title'       => 'Pack système digital complet — ERP/CRM, dev & infra ★ | Complianz',
        'meta_description' => 'Offre signature : site / apps, socle ERP-CRM, intégrations et infrastructure coordonnés. Vision produit de bout en bout. Indicatif 40 000–120 000 €+.',
        'price'            => '40 000–120 000 €+',
        'tagline'          => 'Vous livrez front, back et flux alignés avec un pilotage projet central.',
        'pour_qui'         => 'Scale-up / industrialisation du modèle',
        'signature'        => true,
        'intro'            => 'Pour les organisations qui veulent un partenaire unique sur la chaîne de valeur digitale : cadrage produit, delivery agile, qualité et transfert vers vos équipes ou notre infogérance.',
        'ideal_for'        => [
            'Scale-ups et ETI qui industrialisent leur modèle.',
            'Projets où le site, le back-office et les flux temps réel doivent tenir ensemble.',
            'Directions souhaitant un pilotage budget / risque centralisé.',
        ],
        'deliverables'     => [
            'Architecture solution et roadmap release.',
            'Delivery coordonnée front / back / intégration.',
            'Qualité : tests, observabilité, sécurité by design.',
            'Hypercare et transfert avec documentation vivante.',
        ],
        'duration'         => '6 à 18 mois selon périmètre fonctionnel et nombre de pays.',
        'phases'           => [
            ['title' => 'Produit & architecture', 'text' => 'Vision produit, backlog priorisé, NFR (perf, sécu, disponibilité).'],
            ['title' => 'Construction par releases', 'text' => 'Itérations livrables, démos régulières et gestion du scope.'],
            ['title' => 'Industrialisation', 'text' => 'CI/CD, supervision, PRA simplifié et runbooks.'],
        ],
        'related'          => [
            ['label' => 'ERP sur mesure', 'url' => '/solutions-developpement/erp-crm/erp-sur-mesure'],
            ['label' => 'SaaS', 'url' => '/solutions-developpement/developpement-logiciel/saas'],
            ['label' => 'Cloud & infrastructure', 'url' => '/support-maintenance/infogerance/cloud-infrastructure'],
            ['label' => 'Site e-commerce', 'url' => '/solutions-developpement/creation-site-web/site-ecommerce'],
        ],
        'faq'              => [
            ['q' => 'Qui possède le code et les accès ?', 'a' => 'Contrats clairs sur IP, dépôts, secrets et sauvegardes — vous restez propriétaire de vos données et des livrables convenus.'],
            ['q' => 'Agilité vs cahier des charges ?', 'a' => 'Nous utilisons un backlog priorisé et des jalons contractuels pour concilier flexibilité et prévisibilité financière.'],
            ['q' => 'Après le go-live ?', 'a' => 'Basculer vers le pack « Écosystème complet + suivi » ou une infogérance dédiée pour garder le même interlocuteur.'],
        ],
    ],

    'pack-ecosysteme-complet-suivi' => [
        'title'            => 'Pack Écosystème complet + suivi',
        'pole'             => 1,
        'pole_name'        => 'Solutions & Développement',
        'pole_url'         => '/solutions-developpement',
        'meta_title'       => 'Pack écosystème digital & maintenance continue | Complianz',
        'meta_description' => 'Après la mise en ligne : maintenance, évolutions, support utilisateur et coordination technique en récurrence. Indicatif 2 000–5 000 €/mois.',
        'price'            => '2 000–5 000 €/mois',
        'tagline'          => 'Vos systèmes restent sécurisés et évolutifs sans dérive progressive invisible.',
        'pour_qui'         => 'Plateforme critique sans DSI à plein temps',
        'signature'        => false,
        'intro'            => 'Un dispositif récurrent qui combine astreinte raisonnée, petites évolutions, veille sécurité et accompagnement utilisateurs pour éviter la dérive progressive.',
        'ideal_for'        => [
            'Entreprises sans DSI à temps plein mais avec des enjeux SI réels.',
            'Plateformes critiques pour le chiffre d\'affaires.',
            'Équipes qui veulent une roadmap d\'évolution contrôlée.',
        ],
        'deliverables'     => [
            'Comité technique périodique et backlog d\'évolutions.',
            'Correctifs, mises à jour de dépendances et patchs sécurité.',
            'Support utilisateurs selon SLA défini.',
            'Reporting clair : incidents, changements, dette technique.',
        ],
        'duration'         => 'Contrat 12 mois renouvelable ; préavis selon CC.',
        'phases'           => [
            ['title' => 'Reprise & documentation', 'text' => 'Audit rapide de l\'existant, accès, sauvegardes et risques.'],
            ['title' => 'Stabilisation', 'text' => 'Traitement des dettes urgentes, monitoring et alertes.'],
            ['title' => 'Amélioration continue', 'text' => 'Cadence de releases mineures et arbitrages avec la direction.'],
        ],
        'related'          => [
            ['label' => 'Maintenance évolutive', 'url' => '/support-maintenance/maintenance/maintenance-corrective-evolutive'],
            ['label' => 'Support technique', 'url' => '/support-maintenance/maintenance/support-technique'],
            ['label' => 'Infogérance complète', 'url' => '/support-maintenance/infogerance/infogerance-complete'],
            ['label' => 'Debug & bugs', 'url' => '/support-maintenance/maintenance/debug'],
        ],
        'faq'              => [
            ['q' => 'SLA et horaires ?', 'a' => 'Les plages et temps de réponse sont contractualisés (heures ouvrées / étendues / critiques).'],
            ['q' => 'Évolutions majeures incluses ?', 'a' => 'Un volume d\'évolution est inclus ; au-delà, les projets sont chiffrés en complément avec priorisation transparente.'],
            ['q' => 'Multi-fournisseurs ?', 'a' => 'Nous pouvons coordonner hébergeur, éditeur SaaS et équipes internes avec un point de contact unique.'],
        ],
    ],

    'pack-strategie-fondations-marketing' => [
        'title'            => 'Pack Stratégie & fondations marketing',
        'pole'             => 2,
        'pole_name'        => 'Performance Digitale & Stratégie',
        'pole_url'         => '/performance-digitale',
        'meta_title'       => 'Pack stratégie digitale & fondations marketing | Complianz',
        'meta_description' => 'Positionnement, offres, messages clés, canaux et roadmap d\'actions priorisées — sans dispersion. Indicatif 4 000–10 000 €.',
        'price'            => '4 000–10 000 €',
        'tagline'          => 'Vous savez où mettre le prochain euro marketing au lieu de disperser budget et équipes.',
        'pour_qui'         => 'Marque en repositionnement ou lancement d’offre',
        'signature'        => false,
        'intro'            => 'Avant d\'acheter des pubs ou de produire des contenus à la chaîne, ce pack aligne produit, marché et données disponibles pour décider où investir le prochain euro.',
        'ideal_for'        => [
            'Marques en repositionnement ou lancement d\'offre.',
            'Équipes marketing réduites qui veulent un plan actionnable.',
            'Besoin d\'aligner sales / marketing / produit sur une même histoire.',
        ],
        'deliverables'     => [
            'Ateliers discovery et analyse concurrentielle ciblée.',
            'Personas / ICP et cartographie des parcours prioritaires.',
            'Plan média & contenu priorisé sur 6–12 mois.',
            'KPIs et tableau de bord minimal pour suivre l\'exécution.',
        ],
        'duration'         => '4 à 10 semaines selon nombre de pays / langues.',
        'phases'           => [
            ['title' => 'Diagnostic marché & données', 'text' => 'Audit rapide analytics / CRM / SEO existant et entretiens clients si possible.'],
            ['title' => 'Stratégie & création de valeur', 'text' => 'Choix des batailles, messages et preuves sociales.'],
            ['title' => 'Roadmap & kit de lancement', 'text' => 'Plan trimestriel, budget indicatif et critères de succès.'],
        ],
        'related'          => [
            ['label' => 'Stratégie digitale', 'url' => '/performance-digitale/strategie-digitale'],
            ['label' => 'Marketing digital', 'url' => '/performance-digitale/strategie-digitale/marketing-digital'],
            ['label' => 'SEO', 'url' => '/performance-digitale/seo'],
            ['label' => 'Email marketing', 'url' => '/performance-digitale/strategie-digitale/email-marketing'],
        ],
        'faq'              => [
            ['q' => 'Produisez-vous les contenus ?', 'a' => 'Ce pack définit la stratégie et peut inclure des gabarits ; la production massive peut être ajoutée ou confiée à vos équipes avec nos briefs.'],
            ['q' => 'Publicité incluse ?', 'a' => 'Les budgets médias sont distincts ; nous dimensionnons les tests minimum viables et les critères d\'arrêt.'],
            ['q' => 'International ?', 'a' => 'Extensions multi-langues et adaptations locales possibles avec surcoût maîtrisé.'],
        ],
    ],

    'pack-performance-optimisation-digitale' => [
        'title'            => 'Pack Performance & optimisation digitale',
        'pole'             => 2,
        'pole_name'        => 'Performance Digitale & Stratégie',
        'pole_url'         => '/performance-digitale',
        'meta_title'       => 'Pack SEO + tunnel de conversion — performance digitale | Complianz',
        'meta_description' => 'Combiner visibilité organique et optimisation du tunnel : SEO technique, contenus prioritaires et CRO ciblée. Indicatif 5 000–15 000 €.',
        'price'            => '5 000–15 000 €',
        'tagline'          => 'Vous convertissez plus de visiteurs en opportunités qualifiées (SEO + tunnel).',
        'pour_qui'         => 'Site avec trafic mais peu de leads ou CPA trop élevé',
        'signature'        => false,
        'intro'            => 'Pour les sites qui ont du trafic mais peu de leads, ou des leads mais un coût d\'acquisition trop élevé — nous traitons les deux faces avec une même backlog priorisée.',
        'ideal_for'        => [
            'Sites matures avec analytics exploitable.',
            'Équipes commerciales qui se plaignent de la qualité des leads.',
            'Besoin de quick wins SEO + CRO sans attendre 12 mois.',
        ],
        'deliverables'     => [
            'Audit SEO & revue du tunnel (analytics, heatmaps si besoin).',
            'Correctifs techniques prioritaires et briefs contenus à fort impact.',
            'Tests CRO (pages clés, formulaires, parcours mobile).',
            'Reporting mensuel synthétique orienté ROI.',
        ],
        'duration'         => '3 à 6 mois avec premiers gains dès 4–8 semaines.',
        'phases'           => [
            ['title' => 'Mesure & diagnostic', 'text' => 'Cartographie des fuites et des pages à levier.'],
            ['title' => 'Optimisation par vagues', 'text' => 'Mises en ligne rapides, tests A/B raisonnés.'],
            ['title' => 'Consolidation', 'text' => 'Capitalisation des apprentissages et priorisation long terme.'],
        ],
        'related'          => [
            ['label' => 'SEO technique', 'url' => '/performance-digitale/seo/seo-technique'],
            ['label' => 'CRO', 'url' => '/performance-digitale/tunnel-de-vente/cro'],
            ['label' => 'Tunnel de vente', 'url' => '/performance-digitale/tunnel-de-vente'],
            ['label' => 'Publicité digitale', 'url' => '/performance-digitale/strategie-digitale/publicite-digitale'],
        ],
        'faq'              => [
            ['q' => 'SEO vs SEA dans ce pack ?', 'a' => 'Le focus est organique + conversion ; le SEA peut être utilisé pour valider messages ou mots-clés sans piloter la dépendance long terme.'],
            ['q' => 'Besoin d\'une refonte complète ?', 'a' => 'Souvent non : des corrections ciblées et des tests suffisent ; une refonte est un autre budget que nous signalons clairement si nécessaire.'],
            ['q' => 'Données RGPD / cookies ?', 'a' => 'Nous coordonnons avec vos obligations consentement / CMP pour ne pas « optimiser » au détriment du cadre légal.'],
        ],
    ],

    'pack-performance-digitale-globale' => [
        'title'            => 'Pack Performance digitale globale',
        'pole'             => 2,
        'pole_name'        => 'Performance Digitale & Stratégie',
        'pole_url'         => '/performance-digitale',
        'meta_title'       => 'Pack performance digitale globale — stratégie, SEO, conversion ★ | Complianz',
        'meta_description' => 'Offre signature : stratégie, SEO, acquisition payante, tunnel et pilotage complet — formule projet ou récurrente. Indicatif 12 000–30 000 € ou 1 500–4 000 €/mois.',
        'price'            => '12 000–30 000 € ou 1 500–4 000 €/mois',
        'tagline'          => 'Vous pilotez acquisition et conversion sur des indicateurs business, pas des vanity metrics.',
        'pour_qui'         => 'Croissance nationale / objectifs de pipeline exigeants',
        'signature'        => true,
        'intro'            => 'Pour les directions qui veulent un pilotage unique : campagnes, contenus, optimisation continue et tableaux de bord orientés business plutôt que vanity metrics.',
        'ideal_for'        => [
            'Marques en croissance avec ambition nationale ou europe.',
            'Besoin d\'aligner agences / freelances existants.',
            'Objectifs de pipeline commercial exigeants.',
        ],
        'deliverables'     => [
            'Roadmap trimestrielle intégrant SEO, contenus, paid et CRO.',
            'Rituels de pilotage et arbitrages budgétaires.',
            'Creative & briefs unifiés pour éviter les silos.',
            'Vue consolidée des performances et recommandations continues.',
        ],
        'duration'         => 'Projets 4–9 mois ou abonnement 12 mois renouvelable.',
        'phases'           => [
            ['title' => 'Blueprint & quick wins', 'text' => 'Cartographie des leviers et premières mises en ligne rapides.'],
            ['title' => 'Run & scaling', 'text' => 'Montée en puissance sur les canaux qui prouvent leur ROI.'],
            ['title' => 'Industrialisation', 'text' => 'Playbooks internes, transfert et automatisation du reporting.'],
        ],
        'related'          => [
            ['label' => 'Stratégie digitale globale', 'url' => '/performance-digitale/strategie-digitale'],
            ['label' => 'SEO', 'url' => '/performance-digitale/seo'],
            ['label' => 'Pilotage commercial', 'url' => '/performance-digitale/pilotage-commercial'],
            ['label' => 'Analyse de performance', 'url' => '/performance-digitale/pilotage-commercial/analyse-performance'],
        ],
        'faq'              => [
            ['q' => 'Projet vs récurrent ?', 'a' => 'Le projet pose les bases ; le récurrent assure la cadence d\'optimisation et la réactivité marché — souvent combinés.'],
            ['q' => 'Gestion des médias ?', 'a' => 'Nous pouvons opérer ou coach votre équipe média ; les budgets restent sous votre contrôle direct sur les plateformes si vous le souhaitez.'],
            ['q' => 'Quels indicateurs ?', 'a' => 'Nous privilégions coût par lead qualifié, taux de conversion par étape et contribution au pipeline plutôt que simples impressions.'],
        ],
    ],

    'pack-securite-continuite-technique' => [
        'title'            => 'Pack Sécurité & continuité technique',
        'pole'             => 3,
        'pole_name'        => 'Support & Maintenance',
        'pole_url'         => '/support-maintenance',
        'meta_title'       => 'Pack maintenance, support & hébergement sécurisé | Complianz',
        'meta_description' => 'Maintenance corrective, support utilisateur, supervision et sauvegardes selon vos environnements. Indicatif 300–1 000 €/mois.',
        'price'            => '300–1 000 €/mois',
        'tagline'          => 'Vous gardez correctifs, sauvegardes et incidents suivis avec une vision claire.',
        'pour_qui'         => 'PME sans administrateur système dédié',
        'signature'        => false,
        'intro'            => 'Le socle pour dormir tranquille : surveillance légère sauf besoin critique, application des correctifs, gestion des incidents récurrents et communication claire.',
        'ideal_for'        => [
            'Sites vitrine et applications métiers non 24/7 critiques.',
            'Équipes sans administrateur système à plein temps.',
            'Besoin d\'un filet de sécurité avant projet plus large.',
        ],
        'deliverables'     => [
            'Astreinte ou hotline selon plage horaire contractuelle.',
            'Application des mises à jour mineures et correctifs de sécurité.',
            'Sauvegardes contrôlées et tests de restauration planifiés.',
            'Reporting mensuel incidents / changements.',
        ],
        'duration'         => 'Contrat annuel avec révision trimestrielle du périmètre.',
        'phases'           => [
            ['title' => 'Onboarding technique', 'text' => 'Inventaire, accès sécurisés, sauvegardes et premiers patchs.'],
            ['title' => 'Stabilisation', 'text' => 'Réduction de la dette des alertes et faux positifs.'],
            ['title' => 'Amélioration continue', 'text' => 'Veille CVE ciblée et recommandations proportionnées.'],
        ],
        'related'          => [
            ['label' => 'Maintenance corrective & évolutive', 'url' => '/support-maintenance/maintenance/maintenance-corrective-evolutive'],
            ['label' => 'Hébergement serveur', 'url' => '/support-maintenance/infogerance/hebergement-serveur'],
            ['label' => 'Support technique', 'url' => '/support-maintenance/maintenance/support-technique'],
            ['label' => 'Cloud & infrastructure', 'url' => '/support-maintenance/infogerance/cloud-infrastructure'],
        ],
        'faq'              => [
            ['q' => 'Couvrez-vous le développement applicatif ?', 'a' => 'Les bugs mineurs oui selon SLA ; les évolutions fonctionnelles sont traitées en devis complémentaire.'],
            ['q' => 'Infogérance serveur incluse ?', 'a' => 'Selon formule : nous pouvons inclure ou coordonner avec votre hébergeur existant.'],
            ['q' => 'Engagement minimum ?', 'a' => 'Souvent 12 mois pour amortir l\'onboarding ; possibilité de phase pilote 3 mois sur périmètre réduit.'],
        ],
    ],

    'pack-infogerance-complete' => [
        'title'            => 'Pack Infogérance complète',
        'pole'             => 3,
        'pole_name'        => 'Support & Maintenance',
        'pole_url'         => '/support-maintenance',
        'meta_title'       => 'Pack infogérance complète — infra, hébergement, maintenance ★ | Complianz',
        'meta_description' => 'Offre signature : infogérance, hébergement managé, maintenance applicative et résolution de incidents avec SLA élevé. Indicatif 2 000–5 000 €/mois.',
        'price'            => '2 000–5 000 €/mois',
        'tagline'          => 'Un interlocuteur unique pour dispo, sécurité et résolution incident bout-en-bout.',
        'pour_qui'         => 'SaaS, e-commerce ou plateforme métier critique',
        'signature'        => true,
        'intro'            => 'Pour les environnements où l\'indisponibilité coûte cher : nous portons la responsabilité opérationnelle bout-en-bout avec transparence sur les fenêtres de maintenance et les escalades.',
        'ideal_for'        => [
            'SaaS B2B, e-commerce significatif, plateformes métier critiques.',
            'Organisations soumises à exigences clients ou réglementaires fortes.',
            'Directions qui veulent un interlocuteur unique pour cloud / réseau / app.',
        ],
        'deliverables'     => [
            'Supervision 24/7 ou étendue selon SLA.',
            'Gestion changements, PRA/PCA simplifiés adaptés à votre taille.',
            'Centre de services avec catégorisation incidents / problèmes.',
            'Revues mensuelles ou trimestrielles avec indicateurs clés.',
        ],
        'duration'         => 'Contrat 12–36 mois avec clause de sortie encadrée.',
        'phases'           => [
            ['title' => 'Audit & transition', 'text' => 'Reprise ou création de la documentation d\'exploitation.'],
            ['title' => 'Montée en régime', 'text' => 'Renforcement monitoring, sauvegardes et chemins d\'escalade.'],
            ['title' => 'Optimisation coûts / risques', 'text' => 'Rightsizing, réservations et rationalisation des licences.'],
        ],
        'related'          => [
            ['label' => 'Infogérance complète', 'url' => '/support-maintenance/infogerance/infogerance-complete'],
            ['label' => 'Debug', 'url' => '/support-maintenance/maintenance/debug'],
            ['label' => 'Cloud & infrastructure', 'url' => '/support-maintenance/infogerance/cloud-infrastructure'],
            ['label' => 'Maintenance', 'url' => '/support-maintenance/maintenance'],
        ],
        'faq'              => [
            ['q' => 'Multi-cloud ou legacy ?', 'a' => 'Oui : nous dimensionnons les compétences et outils ; les environnements hybrides sont courants.'],
            ['q' => 'Certifications et accès ?', 'a' => 'Principe du moindre privilège, MFA admin et journalisation des actions sensibles.'],
            ['q' => 'Sortie du contrat ?', 'a' => 'Plan de réversibilité avec transfert configs, sauvegardes et documentation — défini contractuellement.'],
        ],
    ],

    'pack-audit-feuille-route-ia' => [
        'title'            => 'Pack Audit & feuille de route IA',
        'pole'             => 4,
        'pole_name'        => 'Intelligence Artificielle',
        'pole_url'         => '/intelligence-artificielle',
        'meta_title'       => 'Pack audit IA & feuille de route — cas d\'usage & risques | Complianz',
        'meta_description' => 'Identifiez où l\'IA crée de la valeur dans vos processus, avec une analyse risques / données / conformité. Indicatif 3 000–8 000 €.',
        'price'            => '3 000–8 000 €',
        'tagline'          => 'Vous priorisez les cas d\'usage rentables avant licences, GPU ou POC sans lendemain.',
        'pour_qui'         => 'Organisation mature ou fortement contrainte (données, réglementation)',
        'signature'        => false,
        'intro'            => 'Ateliers, revue des données disponibles, évaluation de maturité et feuille de route par vagues (quick wins vs chantiers structurants).',
        'ideal_for'        => [
            'Directions qui veulent éviter les POC sans lendemain.',
            'Organisations soumises au RGPD ou à des contraintes sectorielles.',
            'Équipes qui hésitent entre automatisation classique et IA générative.',
        ],
        'deliverables'     => [
            'Cartographie processus × données × valeur.',
            'Matrice risques (biais, hallucinations, confidentialité).',
            'Feuille de route budgétée et jalons de décision.',
            'Synchronisation avec vos référentiels conformité existants.',
        ],
        'duration'         => '3 à 8 semaines selon nombre de métiers interrogés.',
        'phases'           => [
            ['title' => 'Immersion & cadrage', 'text' => 'Entretiens, inventaire des données et contraintes légales.'],
            ['title' => 'Évaluation & design', 'text' => 'Scénarios de valeur, alternatives sans IA si pertinent.'],
            ['title' => 'Restitution exécutive', 'text' => 'Synthèse COMEX et plan de mise en œuvre par étapes.'],
        ],
        'related'          => [
            ['label' => 'Automatisation IA', 'url' => '/intelligence-artificielle/automatisation-ia'],
            ['label' => 'Formation IA dirigeants', 'url' => '/intelligence-artificielle/formation-ia/formation-ia-pour-dirigeants-d-entreprise'],
            ['label' => 'Conformité IA & AI Act', 'url' => '/intelligence-artificielle/ia-entreprise/conformite-ia-et-ai-act-pour-les-entreprises'],
            ['label' => 'Agents IA', 'url' => '/intelligence-artificielle/agents-ia'],
        ],
        'faq'              => [
            ['q' => 'Inclut-il des développements ?', 'a' => 'Non : c\'est un volet stratégique et d\'architecture ; les développements sont estimés ensuite ou couverts par les packs suivants.'],
            ['q' => 'IA générative ou ML classique ?', 'a' => 'Les deux sont envisagés selon vos données et contraintes ; nous ne préjugons pas d\'une techno avant analyse.'],
            ['q' => 'Données confidentielles ?', 'a' => 'Les échanges peuvent s\'effectuer sous NDA et avec anonymisation des jeux d\'exemples.'],
        ],
    ],

    'pack-automatisation-ia-processus' => [
        'title'            => 'Pack Automatisation IA des processus',
        'pole'             => 4,
        'pole_name'        => 'Intelligence Artificielle',
        'pole_url'         => '/intelligence-artificielle',
        'meta_title'       => 'Pack automatisation IA — workflows, agents, n8n / Make | Complianz',
        'meta_description' => 'Déployez des workflows intelligents : extraction, routage, synthèse et actions connectées à vos outils. Indicatif 5 000–30 000 €.',
        'price'            => '5 000–30 000 €',
        'tagline'          => 'Vous réduisez le traitement manuel avec des flux IA traçables et supervisés.',
        'pour_qui'         => 'Back-office à fort flux documentaire ou ticketing',
        'signature'        => false,
        'intro'            => 'Conception et mise en production d\'automatisations (n8n, Make, agents spécialisés) avec garde-fous humains, logs et reprise sur erreur.',
        'ideal_for'        => [
            'Back-offices à fort volume documentaire ou ticket.',
            'Équipes support / RH / finance cherchant des gains rapides.',
            'Stacks déjà cloud-ready avec API disponibles.',
        ],
        'deliverables'     => [
            'Spécification des flux et politiques de reprise manuelle.',
            'Implémentation connecteurs + prompts / modèles adaptés.',
            'Supervision, métriques de qualité et alertes.',
            'Formation courte aux opérations courantes (prompt tuning léger).',
        ],
        'duration'         => '1 à 4 mois selon nombre d\'intégrations et criticité.',
        'phases'           => [
            ['title' => 'Design & prototype', 'text' => 'POC sur un périmètre restreint avec mesure de fiabilité.'],
            ['title' => 'Industrialisation', 'text' => 'Durcissement sécurité, gestion des secrets, quotas.'],
            ['title' => 'Run & amélioration', 'text' => 'Boucle d\'amélioration continue sur les cas limites.'],
        ],
        'related'          => [
            ['label' => 'Automatisation IA avec n8n', 'url' => '/intelligence-artificielle/automatisation-ia/automatisation-ia-avec-n8n'],
            ['label' => 'Automatisation des processus métiers', 'url' => '/intelligence-artificielle/automatisation-ia/automatisation-des-processus-metiers'],
            ['label' => 'IA agentique', 'url' => '/intelligence-artificielle/agents-ia/ia-agentique'],
            ['label' => 'Automatisation API', 'url' => '/solutions-developpement/developpement-logiciel/automatisation-api'],
        ],
        'faq'              => [
            ['q' => 'Utilisez-vous ChatGPT / Azure / modèles open source ?', 'a' => 'Le choix dépend de vos contraintes de souveraineté, coût et confidentialité ; nous documentons l\'option retenue.'],
            ['q' => 'Qui maintient les prompts ?', 'a' => 'Nous livrons un playbook ; soit votre équipe opère, soit nous via contrat de maintenance.'],
            ['q' => 'RGPD ?', 'a' => 'Analyse d\'impact simplifiée ou complète si traitement de données sensibles ; pseudonymisation lorsque possible.'],
        ],
    ],

    'pack-transformation-ia-complete' => [
        'title'            => 'Pack Transformation IA complète',
        'pole'             => 4,
        'pole_name'        => 'Intelligence Artificielle',
        'pole_url'         => '/intelligence-artificielle',
        'meta_title'       => 'Pack transformation IA complète — audit à déploiement ★ | Complianz',
        'meta_description' => 'Offre signature : audit, architecture données, agents IA, intégration SI, formation et gouvernance. Budget sur devis selon périmètre.',
        'price'            => 'Sur devis',
        'tagline'          => 'Vous passez du POC à une capacité IA durable : données, SI, formation et gouvernance.',
        'pour_qui'         => 'Programme IA multi-métiers ou environnement réglementé',
        'signature'        => true,
        'intro'            => 'Programme complet pour passer de l\'expérimentation à une capacité IA durable au sein de votre SI : gouvernance, mise en production, mesure et adoption.',
        'ideal_for'        => [
            'Directions générales qui veulent un programme unique multi-métiers.',
            'Organisations réglementées ou fortement data-driven.',
            'Projets où la donnée, le SI et la formation doivent avancer ensemble.',
        ],
        'deliverables'     => [
            'Programme gouvernance IA (rôles, validation humaine, indicateurs).',
            'Déploiement de cas d\'usage prioritaires avec intégration SI.',
            'Kit formation managers et utilisateurs clés.',
            'Cadre de mesure valeur / risque et revues trimestrielles initiales.',
        ],
        'duration'         => '6 à 24 mois selon ambition ; phasé par vagues financées.',
        'phases'           => [
            ['title' => 'Fondations & architecture données', 'text' => 'Qualité, accès, sécurité et choix de plateformes.'],
            ['title' => 'Déploiement ciblé', 'text' => 'Mise en production itérative avec indicateurs de fiabilité.'],
            ['title' => 'Scale & culture IA', 'text' => 'Élargissement contrôlé et montée en compétences internes.'],
        ],
        'related'          => [
            ['label' => 'Intégration IA entreprise', 'url' => '/intelligence-artificielle/outils-ia/integration-ia-dans-l-entreprise'],
            ['label' => 'Formation IA générative', 'url' => '/intelligence-artificielle/formation-ia/formation-ia-generative'],
            ['label' => 'Gouvernance des données & IA', 'url' => '/intelligence-artificielle/ia-entreprise/gouvernance-des-donnees-et-ia'],
            ['label' => 'Solutions IA', 'url' => '/intelligence-artificielle/solutions-ia'],
        ],
        'faq'              => [
            ['q' => 'Pourquoi « sur devis » ?', 'a' => 'Le périmètre peut couvrir plusieurs métiers, pays et classes de modèles ; nous fixons des phases budgétées après audit rapide gratuit ou payant selon complexité.'],
            ['q' => 'Change management inclus ?', 'a' => 'Oui sous forme d\'ateliers, supports et indicateurs d\'adoption — dimension critique du succès.'],
            ['q' => 'Interop avec Microsoft / Google / SAP ?', 'a' => 'Oui : nous nous appuyons sur les connecteurs officiels et bonnes pratiques IAM pour limiter les travaux spécifiques.'],
        ],
    ],

];

