<?php

/**
 * Pages « hub » par pôle (/audit-conformite, /solutions-developpement, …).
 *
 * hero_h1       : promesse SEO / business (titre complet pour schema / SEO).
 * hero_hook     : accroche en plusieurs lignes (structure vs catalogue).
 * hero_sub      : précision opérationnelle sous l’accroche (optionnel).
 * hero_badge    : pastille sous le fil d’Ariane (optionnel, ex. « Pôle expertise »).
 * hero_kicker   : ligne courte sous le H1 (optionnel, ex. « RGPD, ISO, organisation »).
 * hero_h1_before / hero_h1_highlight / hero_h1_after : découper le H1 pour surligner un mot (optionnel).
 * hero_illustration / hero_illustration_alt : image hero à droite (optionnel).
 * hero_trust_pillars[] : bandeau — title, text, icon (shield|target|chart|lock).
 * hero_trust_proof     : carte droite — title, sub (optionnel).
 * hero_cta_*    : CTAs hero + bandeau final (cohérence).
 *
 * intro_*       : bande « tension » problème / solution (pages hub).
 *                 intro_conviction (optionnel) active la mise en page « featured » (badge, titre bicolore,
 *                 intro_lead, cartes enrichies, pont central, encadrés résultat, bandeau conviction).
 * highlights    : 3 puces courtes — utilisées par la grille « pôles » sur la home.
 *
 * categories[]  : href, title, text (accroche courte), seo_line (phrase SEO),
 *                 keywords[] (maillons sémantiques), optionnel : href_cases, href_process,
 *                 label_cases, label_process — sinon ancres par défaut #cas-concrets / #processus.
 *                 Optionnel (mise en page « domaines » featured) : accent (blue|green|indigo|purple|orange),
 *                 card_tagline (sous-titre court coloré), icon (chart|shield-check|award|lock|leaf).
 *
 * domains_* (optionnel) : domains_section_badge, domains_title_before / domains_title_highlight / domains_title_after,
 *                 domains_subtitle, domains_carousel_label (aria du carrousel), domains_cta_card (title, text, bullets[],
 *                 cta_label, icon?) — carrousel horizontal + fond bleu nuit si carte CTA présente.
 *
 * seo_deep_section (optionnel) : bloc éditorial long + maillage — title, lead, subsections[],
 *                 wiki_links[], blog_links[], cases_intro, cases_links[].
 *                 Optionnel section « Guide » hub : guide_hero_title_before / guide_hero_title_highlight / guide_hero_title_after,
 *                 guide_hero_sub, guide_search_placeholder, guide_nav[] (label, href, icon, active?),
 *                 guide_start_cards[] (title, text, href, icon, accent blue|green), guide_objectives[] (title, href,
 *                 resources_href, resources_label, icon), guide_popular[] (label, href, icon), guide_news (title, lead,
 *                 cta_label, cta_href, articles[] date|tag|title|href), guide_aside_trust (text sous le CTA latéral).
 *
 * cta_final (optionnel) : bandeau conversion bas de page — title / title_before + title_highlight + title_after,
 *                 text (string ou lignes), text_lines[], badge, microcopy, primary_label, secondary_label (ouvre la modale RDV),
 *                 features[] (icon, title, text), orbit[] (icon, title, subtitle, accent green|blue, pos ; ou label seul).
 *                 Coordonnées : footer du site.
 *
 * packs_hub (optionnel, ex. audit-conformité) : section « Nos packs » enrichie — featured, badge, titres,
 *                 method_steps[], chooser_label, order[] (slugs packs.php), cards[slug] (hub_title, hub_tagline,
 *                 hub_icon (pole-guide-icon : search|layers|monitor|trend|rocket|…), hub_intro, hub_bullets[],
 *                 price_label, duration_label, niveau, accent) — tarif dans l’accordéon « Tarif & détails », cta_diagnostic, cta_expert.
 */
return [
    'audit-conformite' => [
        'pole'                      => 0,
        'path'                      => '/audit-conformite',
        'name'                      => 'Conseil, Audit & Conformité',
        'meta_title'                => 'Audit organisationnel, RGPD & ISO 9001/27001 — méthode et conformité entreprise | Complianz',
        'meta_description'          => 'Audit organisationnel, mise en conformité RGPD, certifications ISO et structuration d’entreprise : périmètres, livrables, audits internes et feuille de route — pour PME et ETI.',
        'hero_h1'                   => 'Audit, structuration et mise en conformité des entreprises',
        'hero_h1_before'            => 'Audit, structuration et mise en ',
        'hero_h1_highlight'         => 'conformité',
        'hero_h1_after'             => ' des entreprises',
        'hero_badge'                => 'Pôle expertise',
        'hero_kicker'               => 'RGPD, ISO, organisation',
        'hero_hook'                 => [
            'Vous ne manquez pas d’outils.',
            'Vous manquez de structure.',
            'Nous transformons votre entreprise en système maîtrisé, conforme et performant.',
        ],
        'hero_sub'                  => '',
        'hero_illustration'         => '/assets/images/illustrations/WebP/Plan%20de%20travail%209.webp',
        'hero_illustration_alt'     => 'Audit, conformité ISO et RGPD, structuration et pilotage d’entreprise — illustration Complianz',
        'hero_trust_pillars'        => [
            ['title' => 'Conformité', 'text' => 'RGPD, ISO et qualité — cadre utile et preuves.', 'icon' => 'shield'],
            ['title' => 'Organisation', 'text' => 'Rôles, processus et décisions lisibles.', 'icon' => 'target'],
            ['title' => 'Performance', 'text' => 'Indicateurs et pilotage reliés au métier.', 'icon' => 'chart'],
            ['title' => 'Sécurité', 'text' => 'Risques maîtrisés et traçabilité.', 'icon' => 'lock'],
        ],
        'hero_trust_proof'          => [
            'title' => '+300 entreprises accompagnées',
            'sub'   => 'Des PME aux ETI, tous secteurs confondus.',
        ],
        'hero_cta_primary'          => 'Diagnostic en priorité',
        'hero_cta_secondary'        => 'Voir comment on travaille',
        'hero_cta_secondary_href'   => '/a-propos',
        'intro_tension_title'       => 'Pourquoi votre conformité vous ralentit au lieu de vous structurer',
        'intro_section_badge'       => 'Notre constat',
        'intro_tension_title_before' => 'Pourquoi votre conformité vous ralentit',
        'intro_tension_title_highlight' => 'au lieu de vous structurer',
        'intro_lead'                => [
            'La conformité ne devrait pas être une contrainte.',
            'Bien intégrée, c’est un levier de performance.',
        ],
        'intro_today_card_title'    => 'Une conformité subie',
        'intro_tomorrow_card_title' => 'Une conformité structurante',
        'intro_today_label'         => 'Aujourd’hui',
        'intro_tomorrow_label'      => 'Demain',
        'intro_problems'            => [
            ['text' => 'Le RGPD est traité « pour être conforme », pas comme un levier utilisé au quotidien.', 'icon' => 'shield'],
            ['text' => 'L’ISO est perçue comme une contrainte administrative, pas comme un cadre utile.', 'icon' => 'file'],
            ['text' => 'Outils, registres et dossiers sont déconnectés de vos processus réels.', 'icon' => 'unlink'],
            ['text' => 'Perte de temps, ressaisies et doublons entre juridique, qualité et opérations.', 'icon' => 'clock'],
        ],
        'intro_solutions'           => [
            ['text' => 'Conformité intégrée à l’organisation — pas à côté du métier.', 'icon' => 'nodes'],
            ['text' => 'Audits et diagnostics orientés ROI et décisions priorisées.', 'icon' => 'target'],
            ['text' => 'Structuration des rôles, règles et outils alignés sur vos flux.', 'icon' => 'puzzle'],
            ['text' => 'Pilotage clair : indicateurs, responsabilités et traçabilité.', 'icon' => 'chart'],
        ],
        'intro_today_result'        => 'Résultat : une organisation lourde, des risques, et une performance qui en pâtit.',
        'intro_tomorrow_result'     => 'Résultat : une organisation maîtrisée, conforme et prête à performer.',
        'intro_conviction'          => [
            'label'     => 'Notre conviction',
            'statement' => 'La conformité n’est pas une fin en soi.',
            'sub'       => 'C’est un système qui, bien conçu, libère du temps, sécurise l’entreprise et améliore vos résultats.',
        ],
        'highlights'                => [
            'Conformité reliée au métier',
            'Audits orientés décision',
            'Moins de doublons, plus de clarté',
        ],
        'seo_deep_section'          => [
            'id'           => 'comprendre-audit-conformite',
            'title'        => 'Comprendre l’audit et la conformité en entreprise',
            'lead'         => 'L’audit et la conformité ne sont pas des « dossiers à produire » : ce sont des leviers pour clarifier la réalité opérationnelle (organisation, données, risques) et décider dans le bon ordre — avant d’investir dans des outils ou des certifications. Sur ce pôle, nous articulons typiquement quatre familles de sujets : l’audit organisationnel (structure et performance), le volet données personnelles (RGPD), les référentiels ISO adaptés à votre secteur, et la structuration durable de l’entreprise (rôles, processus, pilotage).',
            'subsections'  => [
                [
                    'slug'          => 'audit-organisationnel',
                    'title'         => 'Audit organisationnel',
                    'paragraphs'    => [
                        'Un audit organisationnel vise à objectiver comment l’entreprise fonctionne réellement : répartition des rôles, flux entre métiers, goulets d’étranglement, charge et lisibilité pour la direction. Il permet de prioriser des chantiers de structuration et d’éviter les investissements dans le mauvais ordre (outil avant processus, conformité décorrélée du terrain).',
                        'Il se distingue d’un simple rapport RH ou financier : il croise entretiens, documents et usages des SI pour relier cause à effet. Les livrables sont exploitables en COMEX : synthèse, constats et plan d’action priorisé.',
                    ],
                    'service_links' => [
                        ['href' => '/audit-conformite/audit-conseil/audit-organisationnel', 'label' => 'Audit organisationnel'],
                        ['href' => '/audit-conformite/audit-conseil/structuration-gouvernance', 'label' => 'Structuration & gouvernance'],
                        ['href' => '/audit-conformite/audit-conseil', 'label' => 'Audit global & conseil stratégique'],
                    ],
                ],
                [
                    'slug'          => 'audit-rgpd',
                    'title'         => 'Audit RGPD et mise en conformité données personnelles',
                    'paragraphs'    => [
                        'Le RGPD impose une traçabilité entre finalités, données, bases légales et mesures de sécurité proportionnées. Un audit RGPD ne se limite pas à une checklist : il aligne les traitements réels sur le registre, identifie les écarts à risque et propose des corrections tenables pour les équipes.',
                        'La conformité utile est celle qui protège l’entreprise tout en restant utilisable au quotidien (procédures courtes, responsabilités claires, preuves pour les contrôles).',
                    ],
                    'service_links' => [
                        ['href' => '/audit-conformite/conformite-rgpd/audit-rgpd', 'label' => 'Audit RGPD'],
                        ['href' => '/audit-conformite/conformite-rgpd', 'label' => 'Mise en conformité RGPD'],
                        ['href' => '/audit-conformite/conformite-rgpd/registre-traitements', 'label' => 'Registre des traitements'],
                    ],
                ],
                [
                    'slug'          => 'certification-iso',
                    'title'         => 'Certification ISO (9001, 27001, SMQ)',
                    'paragraphs'    => [
                        'Les référentiels ISO donnent un langage commun à la direction, aux métiers et aux audits : exigences, preuves et amélioration continue. Selon votre maturité, la préparation peut combiner ISO 9001 (management de la qualité), ISO 27001 (sécurité de l’information) ou la mise en place d’un SMQ avant certification.',
                        'L’objectif n’est pas la « paperasse » : c’est un cadre pour sécuriser la relation client, industrialiser les processus critiques et répondre aux exigences clients ou appels d’offres.',
                    ],
                    'service_links' => [
                        ['href' => '/audit-conformite/certifications-iso', 'label' => 'Accompagnement certifications ISO'],
                        ['href' => '/audit-conformite/certifications-iso/iso-9001', 'label' => 'Certification ISO 9001'],
                        ['href' => '/audit-conformite/certifications-iso/iso-27001', 'label' => 'Certification ISO 27001'],
                        ['href' => '/audit-conformite/certifications-iso/audit-qualite', 'label' => 'Audit qualité interne'],
                    ],
                ],
                [
                    'slug'          => 'structuration-entreprise',
                    'title'         => 'Structuration de l’entreprise',
                    'paragraphs'    => [
                        'Structurer, c’est rendre explicites les règles du jeu : qui décide, qui produit la donnée de référence, comment les interfaces métier–SI sont tenues. Sans cette couche, les projets digitaux et les démarches conformité démultiplient les silos.',
                        'La structuration relie souvent audit organisationnel, référentiels qualité / sécurité et pilotage par indicateurs — avec des jalons réalistes pour les équipes.',
                    ],
                    'service_links' => [
                        ['href' => '/audit-conformite/audit-conseil/structuration-gouvernance', 'label' => 'Structuration & gouvernance'],
                        ['href' => '/audit-conformite/conformite-rgpd/dpo-externalise', 'label' => 'DPO externalisé'],
                        ['href' => '/audit-conformite/cybersecurite', 'label' => 'Cybersécurité & politique de sécurité'],
                    ],
                ],
            ],
            'wiki_links'   => [
                ['href' => '/wiki/flux-et-donnees', 'label' => 'Wiki — Flux & cycle de vie des données'],
                ['href' => '/wiki/introduction', 'label' => 'Wiki — Introduction & navigation'],
            ],
            'blog_links'   => [
                ['href' => '/blog/audit-entreprise-guide-complet-2024', 'label' => 'Blog — Audit d’entreprise : guide méthode'],
                ['href' => '/blog/registre-traitements-rgpd-mise-a-jour', 'label' => 'Blog — Registre RGPD : mise à jour utile'],
                ['href' => '/blog/iso-27001-premiers-pas-pme', 'label' => 'Blog — ISO 27001 : premiers pas en PME'],
            ],
            'guide_hero_title_before'   => 'Le guide complet de la ',
            'guide_hero_title_highlight' => 'conformité',
            'guide_hero_title_after'    => ' et de la performance',
            'guide_hero_sub'            => 'Parcours par thématique, ressources actionnables et actualités : tout pour comprendre, prioriser et avancer avec méthode.',
            'guide_search_placeholder'  => 'Rechercher un sujet, un guide, une norme…',
            'guide_nav'                 => [
                ['label' => 'Vue d’ensemble', 'href' => '#pole-guide-title', 'icon' => 'target', 'active' => true],
                ['label' => 'Audit & diagnostic', 'href' => '/audit-conformite/audit-conseil/audit-organisationnel', 'icon' => 'search'],
                ['label' => 'Conformité & sécurité', 'href' => '/audit-conformite/conformite-rgpd', 'icon' => 'shield'],
                ['label' => 'Normes & certifications', 'href' => '/audit-conformite/certifications-iso', 'icon' => 'award'],
                ['label' => 'Structuration & gouvernance', 'href' => '/audit-conformite/audit-conseil/structuration-gouvernance', 'icon' => 'layers'],
                ['label' => 'Outils & digitalisation', 'href' => '/wiki/flux-et-donnees', 'icon' => 'gear'],
                ['label' => 'Cas pratiques', 'href' => '/blog?pole=0', 'icon' => 'file'],
                ['label' => 'Guides méthodologiques', 'href' => '/wiki', 'icon' => 'book'],
                ['label' => 'Ressources gratuites', 'href' => '/blog', 'icon' => 'wiki'],
            ],
            'guide_start_cards'         => [
                [
                    'title'   => 'Comprendre la conformité',
                    'text'    => 'Cadre RGPD, ISO et audit : enjeux, livrables et ordre des priorités pour la direction.',
                    'href'    => '/audit-conformite/conformite-rgpd',
                    'icon'    => 'shield',
                    'accent'  => 'green',
                ],
                [
                    'title'   => 'Diagnostiquer sans perdre de temps',
                    'text'    => 'Méthode d’audit organisationnel : constats exploitables et plan d’action priorisé.',
                    'href'    => '/audit-conformite/audit-conseil/audit-organisationnel',
                    'icon'    => 'search',
                    'accent'  => 'blue',
                ],
                [
                    'title'   => 'Préparer une certification',
                    'text'    => 'ISO 9001, 27001 : préparation réaliste, preuves utiles et conduite du changement.',
                    'href'    => '/audit-conformite/certifications-iso',
                    'icon'    => 'award',
                    'accent'  => 'blue',
                ],
                [
                    'title'   => 'Structurer pour durer',
                    'text'    => 'Rôles, processus et pilotage : les bases avant outillage et conformité « décorrélée ».',
                    'href'    => '/audit-conformite/audit-conseil/structuration-gouvernance',
                    'icon'    => 'layers',
                    'accent'  => 'green',
                ],
            ],
            'guide_objectives'          => [
                [
                    'title'            => 'Se mettre en conformité',
                    'href'             => '/audit-conformite/conformite-rgpd',
                    'resources_href'   => '/wiki',
                    'resources_label'  => 'Voir les ressources',
                    'icon'             => 'shield',
                ],
                [
                    'title'            => 'Sécuriser & certifier',
                    'href'             => '/audit-conformite/certifications-iso',
                    'resources_href'   => '/wiki/introduction',
                    'resources_label'  => 'Voir les ressources',
                    'icon'             => 'award',
                ],
                [
                    'title'            => 'Structurer & piloter',
                    'href'             => '/audit-conformite/audit-conseil/structuration-gouvernance',
                    'resources_href'   => '/wiki/flux-et-donnees',
                    'resources_label'  => 'Voir les ressources',
                    'icon'             => 'layers',
                ],
                [
                    'title'            => 'Diagnostiquer avant d’investir',
                    'href'             => '/audit-conformite/audit-conseil/audit-organisationnel',
                    'resources_href'   => '/blog?pole=0',
                    'resources_label'  => 'Voir les ressources',
                    'icon'             => 'search',
                ],
            ],
            'guide_popular'             => [
                ['label' => 'Audit organisationnel : par où commencer ?', 'href' => '/blog/audit-entreprise-guide-complet-2024', 'icon' => 'search'],
                ['label' => 'Registre RGPD : mise à jour utile', 'href' => '/blog/registre-traitements-rgpd-mise-a-jour', 'icon' => 'shield'],
                ['label' => 'ISO 27001 : premiers pas en PME', 'href' => '/blog/iso-27001-premiers-pas-pme', 'icon' => 'award'],
                ['label' => 'Flux & cycle de vie des données', 'href' => '/wiki/flux-et-donnees', 'icon' => 'file'],
                ['label' => 'Introduction wiki & navigation', 'href' => '/wiki/introduction', 'icon' => 'book'],
                ['label' => 'Mise en conformité RGPD', 'href' => '/audit-conformite/conformite-rgpd', 'icon' => 'lock'],
                ['label' => 'Certifications ISO', 'href' => '/audit-conformite/certifications-iso', 'icon' => 'badge'],
                ['label' => 'Structuration & gouvernance', 'href' => '/audit-conformite/audit-conseil/structuration-gouvernance', 'icon' => 'layers'],
            ],
            'guide_news'                => [
                'title'     => 'Nouveautés & bonnes pratiques',
                'lead'      => 'Articles méthode, points de vigilance et retours d’expérience pour avancer sans surcouches inutiles.',
                'cta_label' => 'Découvrir les derniers articles',
                'cta_href'  => '/blog?pole=0',
                'articles'  => [
                    [
                        'date' => '12 mai 2026',
                        'tag'  => 'RGPD',
                        'title' => 'Registre des traitements : ce que les contrôleurs regardent vraiment',
                        'href' => '/blog/registre-traitements-rgpd-mise-a-jour',
                    ],
                    [
                        'date' => '3 avr. 2026',
                        'tag'  => 'ISO',
                        'title' => 'ISO 27001 en PME : par où commencer sans surdimensionner',
                        'href' => '/blog/iso-27001-premiers-pas-pme',
                    ],
                    [
                        'date' => '22 févr. 2026',
                        'tag'  => 'Audit',
                        'title' => 'Audit d’entreprise : méthode et livrables utiles à la direction',
                        'href' => '/blog/audit-entreprise-guide-complet-2024',
                    ],
                ],
            ],
            'guide_aside_trust'         => 'Réponse sous 24h',
            'cases_intro'  => 'Les livrables et contextes clients sont souvent confidentiels ; nous pouvons présenter des cas anonymisés ou des références sur secteur après qualification.',
            'cases_links'  => [
                ['href' => '/blog?pole=0', 'label' => 'Articles — retours d’expérience (pôle Audit & conformité)'],
                ['href' => '/contact', 'label' => 'Échanger sur un cas comparable ou une référence'],
            ],
        ],
        'domains_section_badge'     => 'Expertises',
        'domains_title_before'      => 'Nos domaines d’expertise ',
        'domains_title_highlight'   => 'pour structurer et sécuriser',
        'domains_title_after'       => ' votre entreprise',
        'domains_subtitle'          => 'Chaque domaine répond à une intention précise avec une approche méthodique et des livrables concrets pour des résultats mesurables.',
        'domains_cta_card'          => [
            'title'    => 'Une approche globale et intégrée',
            'text'     => 'Nos expertises sont conçues pour travailler ensemble et créer un système cohérent, conforme et performant.',
            'bullets'  => [
                'Méthodologie éprouvée',
                'Livrables concrets et actionnables',
                'Experts métiers & réglementaires',
                'Accompagnement sur le long terme',
            ],
            'cta_label' => 'Échanger avec un expert',
        ],
        'categories'                => [
            [
                'href'         => '/audit-conformite/audit-conseil',
                'title'        => 'Audit global & Conseil',
                'text'         => 'Diagnostic organisationnel, cartographie des priorités et feuille de route partagée avec la direction — pour décider dans le bon ordre avant d’investir.',
                'seo_line'     => 'Audit global d’entreprise : analyse organisationnelle, processus, outils et performance.',
                'card_tagline' => 'Vision claire. Priorités alignées.',
                'accent'       => 'blue',
                'icon'         => 'chart',
                'keywords'     => ['audit organisationnel', 'structuration entreprise', 'gouvernance', 'audit performance'],
            ],
            [
                'href'         => '/audit-conformite/conformite-rgpd',
                'title'        => 'Mise en conformité RGPD',
                'text'         => 'Alignement des traitements sur le registre, mesures proportionnées et preuves exploitables — une conformité utile au quotidien, pas seulement sur le papier.',
                'seo_line'     => 'Conformité RGPD opérationnelle : données personnelles, registre des traitements et risques maîtrisés.',
                'card_tagline' => 'Données maîtrisées. Risques réduits.',
                'accent'       => 'green',
                'icon'         => 'shield-check',
                'keywords'     => ['audit RGPD', 'conformité données personnelles', 'DPO externalisé', 'registre RGPD'],
            ],
            [
                'href'         => '/audit-conformite/certifications-iso',
                'title'        => 'Certifications ISO',
                'text'         => 'Préparation ISO 9001, ISO 27001 ou SMQ : exigences traduites en processus tenables, audits internes et dossiers de certification structurants.',
                'seo_line'     => 'Certifications ISO 9001 et ISO 27001 : préparation, audits qualité et système de management.',
                'card_tagline' => 'Normes maîtrisées. Qualité prouvée.',
                'accent'       => 'indigo',
                'icon'         => 'award',
                'keywords'     => ['certification ISO 9001', 'ISO 27001', 'SMQ', 'audit qualité interne'],
            ],
            [
                'href'         => '/audit-conformite/cybersecurite',
                'title'        => 'Cybersécurité',
                'text'         => 'Audit, durcissement et politique de sécurité alignés sur vos risques métiers — pour protéger l’activité sans paralysie administrativo-technique.',
                'seo_line'     => 'Cybersécurité PME et ETI : audit, durcissement et politique de sécurité alignée sur vos risques.',
                'card_tagline' => 'Systèmes protégés. Activité sécurisée.',
                'accent'       => 'purple',
                'icon'         => 'lock',
                'keywords'     => ['cybersécurité PME', 'audit cyber', 'pentest', 'politique de sécurité'],
            ],
            [
                'href'         => '/audit-conformite/rse',
                'title'        => 'Démarche RSE',
                'text'         => 'Stratégie RSE, bilan carbone et reporting extra-financier reliés à vos enjeux business — indicateurs lisibles pour la direction et les parties prenantes.',
                'seo_line'     => 'RSE et reporting : stratégie, bilan carbone, labels et indicateurs extra-financiers.',
                'card_tagline' => 'Impact mesuré. Valeur durable.',
                'accent'       => 'orange',
                'icon'         => 'leaf',
                'keywords'     => ['stratégie RSE', 'bilan carbone entreprise', 'label RSE', 'reporting ESG'],
            ],
        ],
        'packs_hub'                 => [
            'featured'          => true,
            'badge'             => 'Nos parcours packagés',
            'title_before'      => 'Des parcours clairs pour des entreprises ',
            'title_highlight'   => 'structurées, conformes et performantes',
            'title_after'       => '',
            'subtitle'          => 'Chaque parcours correspond à un niveau de maturité. Vous progressez étape par étape vers un système global maîtrisé et durable.',
            'method_label'      => 'Notre méthode en 5 étapes',
            'method_steps'      => [
                ['title' => '1. Diagnostic', 'text' => 'Comprendre votre situation et vos priorités'],
                ['title' => '2. Structuration', 'text' => 'Poser des bases solides et des règles claires'],
                ['title' => '3. Digitalisation', 'text' => 'Outiller et automatiser sans déraper'],
                ['title' => '4. Performance', 'text' => 'Mesurer, ajuster et gagner en efficience'],
                ['title' => '5. Pilotage', 'text' => 'Tenir le cap et faire grandir le système'],
            ],
            'chooser_label'     => 'Choisissez le parcours adapté à votre niveau de maturité',
            'order'             => [
                'pack-diagnostic-vision',
                'pack-mise-en-conformite-securisation',
                'pack-structuration-organisation',
                'pack-structuration-performance-globale',
                'pack-direction-strategique-externalisee',
            ],
            'cards'             => [
                'pack-diagnostic-vision'                   => [
                    'niveau'         => 1,
                    'accent'         => 'blue',
                    'hub_title'      => 'Pack Diagnostic',
                    'hub_tagline'    => 'Clarté & priorités',
                    'hub_icon'       => 'search',
                    'hub_intro'      => 'Faites le point et identifiez vos leviers prioritaires.',
                    'hub_bullets'    => ['Audit organisationnel', 'Analyse des risques', 'Feuille de route priorisée'],
                    'price_label'    => '3 000 - 7 000 €',
                    'duration_label' => 'Durée : 2 à 4 semaines',
                ],
                'pack-mise-en-conformite-securisation'     => [
                    'niveau'         => 2,
                    'accent'         => 'green',
                    'hub_title'      => 'Pack Structuration',
                    'hub_tagline'    => 'Bases solides',
                    'hub_icon'       => 'layers',
                    'hub_intro'      => 'Structurez vos processus, rôles et outils clés.',
                    'hub_bullets'    => ['Cartographie des processus', 'Rôles & gouvernance', 'Outils & méthodes'],
                    'price_label'    => '8 000 - 20 000 €',
                    'duration_label' => 'Durée : 1 à 2 mois',
                ],
                'pack-structuration-organisation'          => [
                    'niveau'         => 3,
                    'accent'         => 'blue',
                    'hub_title'      => 'Pack Digitalisation',
                    'hub_tagline'    => 'Efficacité & automatisation',
                    'hub_icon'       => 'monitor',
                    'hub_intro'      => 'Déployez les outils adaptés et automatisez vos flux.',
                    'hub_bullets'    => ['Choix & déploiement d’outils', 'Intégrations & automatisations', 'Formation & adoption'],
                    'price_label'    => '10 000 - 30 000 €',
                    'duration_label' => 'Durée : 1 à 3 mois',
                ],
                'pack-structuration-performance-globale'   => [
                    'niveau'         => 4,
                    'accent'         => 'green',
                    'hub_title'      => 'Pack Performance',
                    'hub_tagline'    => 'Pilotage & optimisation',
                    'hub_icon'       => 'trend',
                    'hub_intro'      => 'Pilotez vos indicateurs et optimisez vos performances.',
                    'hub_bullets'    => ['Tableaux de bord & KPI', 'Optimisation des processus', 'Accompagnement au pilotage'],
                    'price_label'    => '15 000 - 40 000 €',
                    'duration_label' => 'Durée : 2 à 4 mois',
                ],
                'pack-direction-strategique-externalisee'  => [
                    'niveau'         => 5,
                    'accent'         => 'blue',
                    'hub_title'      => 'Pack Pilotage',
                    'hub_tagline'    => 'Autonomie & croissance',
                    'hub_icon'       => 'rocket',
                    'hub_intro'      => 'Gagnez en autonomie et améliorez en continu.',
                    'hub_bullets'    => ['Système de management', 'Amélioration continue', 'Transfert de compétences'],
                    'price_label'    => 'Sur devis',
                    'duration_label' => 'Durée : continue',
                ],
            ],
            'cta_diagnostic'    => [
                'text'         => 'Quel parcours est fait pour vous ? Répondez à 6 questions et obtenez une recommandation personnalisée selon votre maturité et vos enjeux.',
                'button_label' => 'Faire le diagnostic gratuit',
                'footnote'     => 'Sans engagement · 2 minutes',
            ],
            'cta_expert'        => [
                'text'       => 'Besoin d’un accompagnement sur-mesure ? Échangez avec un expert pour construire le parcours le plus adapté à vos enjeux.',
                'link_label' => 'Prendre rendez-vous',
                'href'       => '/contact',
            ],
        ],
        'cta_final'             => [
            'badge'             => 'Passer à l\'action',
            'title_before'      => 'Prêt à structurer votre entreprise et à ',
            'title_highlight'   => 'libérer tout son potentiel ?',
            'title_after'       => '',
            'text'              => [
                'Identifiez vos priorités avec un diagnostic rapide, puis alignez conformité, organisation et pilotage.',
                'Sans engagement : vous repartez avec une vision claire et des prochaines étapes concrètes.',
            ],
            'microcopy'         => 'Sans engagement • 2 minutes',
            'primary_label'     => 'Faire un diagnostic gratuit',
            'secondary_label'   => 'Être rappelé par un expert',
            'features'          => [
                ['icon' => 'search', 'title' => 'Vision claire', 'text' => 'Priorités et risques mis à plat avant d\'investir.'],
                ['icon' => 'clock', 'title' => 'Gain de temps', 'text' => 'Moins de ressaisies et de dossiers « pour la forme ».'],
                ['icon' => 'shield', 'title' => 'Conformité utile', 'text' => 'RGPD et ISO reliés à vos processus réels.'],
                ['icon' => 'chart', 'title' => 'Pilotage mesurable', 'text' => 'Indicateurs lisibles pour la direction et les équipes.'],
            ],
            'orbit'             => [
                ['icon' => 'target', 'title' => 'Stratégie', 'subtitle' => 'Alignée', 'accent' => 'green', 'pos' => 'tl'],
                ['icon' => 'shield', 'title' => 'Conformité', 'subtitle' => 'Maîtrisée', 'accent' => 'blue', 'pos' => 'tr'],
                ['icon' => 'gear', 'title' => 'Processus', 'subtitle' => 'Optimisés', 'accent' => 'blue', 'pos' => 'bl'],
                ['icon' => 'chart', 'title' => 'Performance', 'subtitle' => 'Durable', 'accent' => 'green', 'pos' => 'br'],
            ],
        ],
    ],

    'solutions-developpement' => [
        'pole'                      => 1,
        'path'                      => '/solutions-developpement',
        'name'                      => 'Solutions & Développement',
        'meta_title'                => 'Sites web, ERP/CRM et logiciels métiers — intégrés à votre système d’entreprise | Complianz',
        'meta_description'          => 'Création web, intégration ERP/CRM, applications métiers et SaaS : des solutions alignées sur vos processus et documentées pour vos équipes.',
        'hero_h1'                   => 'Sites web, ERP/CRM et logiciels métiers — pensés comme des briques de votre système d’entreprise',
        'hero_hook'                 => [
            'La technologie seule ne suffit pas.',
            'Ce qui compte, c’est l’alignement avec vos processus.',
            'Nous livrons des outils digitaux intégrés : vitrine, back-office, automatisation, sans empiler les silos.',
        ],
        'hero_sub'                  => 'Spécifications partagées avec les métiers, architectures maintenables et transfert de compétences — des livrables opérationnels, pas des gadgets.',
        'hero_cta_primary'          => 'Diagnostic en priorité',
        'hero_cta_secondary'        => 'Voir comment on travaille',
        'hero_cta_secondary_href'   => '/a-propos',
        'intro_tension_title'       => 'Pourquoi vos outils ajoutent des couches au lieu de fluidifier tout le système',
        'intro_today_label'         => 'Aujourd’hui',
        'intro_tomorrow_label'      => 'Demain',
        'intro_problems'            => [
            'Sites, ERP et scripts vivent en silos : peu de vision transverse.',
            'Spécifications floues → écarts en prod et dette technique invisible.',
            'Interfaces pensées pour « livrer », pas pour être tenues par les métiers.',
            'Reporting fragmenté : chaque outil raconte une histoire différente.',
        ],
        'intro_solutions'           => [
            'Architecture et choix techniques alignés sur vos processus réels.',
            'Ateliers métiers avant build : périmètre et critères d’acceptation partagés.',
            'Intégrations et automatisation sans multiplier les silos inutiles.',
            'Documentation et transfert pour que le système reste maîtrisé dans la durée.',
        ],
        'highlights'                => [
            'Specs co-construites avec les métiers',
            'ERP / APIs sans silos',
            'Doc & transfert équipes',
        ],
        'categories'                => [
            [
                'href'     => '/solutions-developpement/creation-site-web',
                'title'    => 'Création de sites web',
                'text'     => 'Vitrine, e-commerce, refonte, landing pages, WordPress & CMS.',
                'seo_line' => 'Sites vitrine et e-commerce : conception orientée conversion, performance technique et SEO de base.',
                'keywords' => ['création site vitrine', 'site e-commerce', 'refonte WordPress', 'landing page'],
            ],
            [
                'href'     => '/solutions-developpement/erp-crm',
                'title'    => 'ERP & CRM sur mesure',
                'text'     => 'CRM, ERP, gestion commerciale, intégration Odoo et SI existants.',
                'seo_line' => 'ERP et CRM alignés sur vos processus : intégration, automatisation et données partagées.',
                'keywords' => ['ERP sur mesure', 'CRM entreprise', 'intégration Odoo', 'gestion commerciale'],
            ],
            [
                'href'     => '/solutions-developpement/developpement-logiciel',
                'title'    => 'Développement logiciel & SaaS',
                'text'     => 'Applications métier, SaaS, automatisation & API.',
                'seo_line' => 'Applications métiers et SaaS : API, automatisation, sécurité et industrialisation des releases.',
                'keywords' => ['développement logiciel métier', 'SaaS B2B', 'API entreprise', 'automatisation SI'],
            ],
        ],
    ],

    'performance-digitale' => [
        'pole'                      => 2,
        'path'                      => '/performance-digitale',
        'name'                      => 'Performance Digitale & Stratégie',
        'meta_title'                => 'Performance digitale — visibilité, acquisition et pilotage reliés au business | Complianz',
        'meta_description'          => 'SEO, tunnels de conversion et pilotage commercial : une performance digitale mesurable, branchée sur vos objectifs et vos données.',
        'hero_h1'                   => 'Visibilité, acquisition et pilotage — une performance digitale reliée à vos objectifs business',
        'hero_hook'                 => [
            'Le trafic seul ne paie pas les factures.',
            'Ce qui compte, c’est le système qui convertit et qui pilote.',
            'Nous lions stratégie, contenus et données pour un ROI lisible par la direction.',
        ],
        'hero_sub'                  => 'SEO, tunnels, acquisition et tableaux de bord : des décisions basées sur les faits, pas sur les vanity metrics.',
        'hero_cta_primary'          => 'Diagnostic en priorité',
        'hero_cta_secondary'        => 'Voir comment on travaille',
        'hero_cta_secondary_href'   => '/a-propos',
        'intro_tension_title'       => 'Pourquoi votre acquisition alimente des rapports… mais pas la marge',
        'intro_today_label'         => 'Aujourd’hui',
        'intro_tomorrow_label'      => 'Demain',
        'intro_problems'            => [
            'SEO et campagnes décorrélées du CRM et du réel parcours client.',
            'Tunnel « marketing » vs tunnel « vente » : deux langages, peu de convergences.',
            'Optimisations locales sans lien avec la capacité commerciale à traiter les leads.',
            'Vanity metrics : on mesure l’activité, pas la contribution au résultat.',
        ],
        'intro_solutions'           => [
            'Une chaîne unique : visibilité → qualification → conversion mesurable.',
            'Parcours et messages co-construits avec les équipes commerciales.',
            'Tableaux de bord reliés aux sources de vérité (CRM, marges, pipeline).',
            'Décisions marketing / vente / direction parlant le même langage.',
        ],
        'highlights'                => [
            'Acquisition reliée au CRM',
            'Tunnels co-construits avec la vente',
            'Pilotage orienté résultat',
        ],
        'categories'                => [
            [
                'href'     => '/performance-digitale/seo',
                'title'    => 'Référencement naturel (SEO)',
                'text'     => 'Audit SEO, local, technique, netlinking et stratégie de contenu.',
                'seo_line' => 'SEO technique et éditorial : visibilité durable alignée sur la recherche et le business.',
                'keywords' => ['audit SEO', 'SEO local', 'référencement naturel', 'contenu SEO'],
            ],
            [
                'href'     => '/performance-digitale/tunnel-de-vente',
                'title'    => 'Tunnels de conversion',
                'text'     => 'Création de tunnels, CRO et optimisation du taux de conversion.',
                'seo_line' => 'Tunnels de vente et CRO : parcours mesurables du clic au closing.',
                'keywords' => ['tunnel de vente', 'CRO', 'optimisation conversion', 'landing funnel'],
            ],
            [
                'href'     => '/performance-digitale/strategie-digitale',
                'title'    => 'Stratégie digitale',
                'text'     => 'Marketing digital, email, publicité en ligne et réseaux sociaux.',
                'seo_line' => 'Stratégie digitale omnicanale : acquisition, nurturing et cohérence avec les ventes.',
                'keywords' => ['stratégie digitale', 'marketing acquisition', 'email marketing', 'publicité en ligne'],
            ],
            [
                'href'     => '/performance-digitale/pilotage-commercial',
                'title'    => 'Pilotage commercial',
                'text'     => 'Tableaux de bord, analyse de performance et data pour la direction.',
                'seo_line' => 'Pilotage commercial et data : pipeline, prévisions et décisions basées sur les faits.',
                'keywords' => ['tableau de bord commercial', 'data vente', 'pilotage pipeline', 'performance marketing'],
            ],
        ],
    ],

    'support-maintenance' => [
        'pole'                      => 3,
        'path'                      => '/support-maintenance',
        'name'                      => 'Support & Maintenance',
        'meta_title'                => 'Infogérance, maintenance et continuité de service — SLA clairs, système maîtrisé | Complianz',
        'meta_description'          => 'Infogérance, hébergement managé, maintenance corrective et évolutive : garder vos systèmes disponibles, sécurisés et traçables.',
        'hero_h1'                   => 'Infogérance et maintenance — pour que vos systèmes restent disponibles, sécurisés et évolutifs',
        'hero_hook'                 => [
            'Les incidents tombent toujours au pire moment.',
            'La réponse, c’est une exploitation claire et contractualisée.',
            'Nous assurons continuité, correctifs et évolutions — avec un interlocuteur unique.',
        ],
        'hero_sub'                  => 'Supervision, mises à jour, sauvegardes et petites évolutions : des engagements précis, pas du « best effort » opaque.',
        'hero_cta_primary'          => 'Diagnostic en priorité',
        'hero_cta_secondary'        => 'Voir comment on travaille',
        'hero_cta_secondary_href'   => '/a-propos',
        'intro_tension_title'       => 'Pourquoi l’exploitation reste du réactif au lieu d’un système sous contrôle',
        'intro_today_label'         => 'Aujourd’hui',
        'intro_tomorrow_label'      => 'Demain',
        'intro_problems'            => [
            'Tickets et astreintes sans lien clair avec la criticité métier.',
            'Mises à jour « quand on peut », traçabilité faible des changements.',
            'Hébergeur, éditeur, intégrateur : la balle passe, personne ne porte la vue d’ensemble.',
            'Indisponibilités découvertes par les utilisateurs, pas avant.',
        ],
        'intro_solutions'           => [
            'SLA et plages horaires adaptés à votre criticité réelle.',
            'Supervision, patchs et sauvegardes avec historique et responsabilité.',
            'Guichet unique : coordination fournisseurs et équipes.',
            'Évolutions petites mais régulières pour éviter les big bang risqués.',
        ],
        'highlights'                => [
            'SLA clairs & traçabilité',
            'Un interlocuteur unique',
            'Continuité mesurable',
        ],
        'categories'                => [
            [
                'href'     => '/support-maintenance/infogerance',
                'title'    => 'Infogérance & Hébergement',
                'text'     => 'Infogérance complète, serveurs dédiés, VPS, cloud et infrastructure managée.',
                'seo_line' => 'Infogérance et hébergement managé : disponibilité, sauvegardes et supervision pour PME et ETI.',
                'keywords' => ['infogérance serveur', 'hébergement managé', 'cloud entreprise', 'supervision infrastructure'],
            ],
            [
                'href'     => '/support-maintenance/maintenance',
                'title'    => 'Maintenance & Support technique',
                'text'     => 'Maintenance corrective & évolutive, debug, support externalisé.',
                'seo_line' => 'Maintenance applicative et support : correctifs, évolutions et SLA selon votre criticité.',
                'keywords' => ['maintenance applicative', 'support technique IT', 'correctifs production', 'SLA maintenance'],
            ],
        ],
    ],

    'intelligence-artificielle' => [
        'pole'                      => 4,
        'path'                      => '/intelligence-artificielle',
        'name'                      => 'Intelligence Artificielle',
        'meta_title'                => 'IA en entreprise — diagnostic, intégration et gouvernance pour un système fiable | Complianz',
        'meta_description'          => 'Agents IA, automatisation, formation : passer du POC à la production avec traçabilité, conformité et valeur métier mesurable.',
        'hero_h1'                   => 'Intelligence artificielle utile et encadrée — du diagnostic à la mise en production',
        'hero_hook'                 => [
            'L’IA ne remplace pas votre stratégie.',
            'Elle l’accélère lorsqu’elle est cadrée.',
            'Nous priorisons les cas d’usage, intégrons au SI et posons la gouvernance données & modèles.',
        ],
        'hero_sub'                  => 'Automatisation, agents IA, formation : des livrables opérationnels avec garde-fous — pas de couches gadgets sans processus clairs.',
        'hero_cta_primary'          => 'Diagnostic en priorité',
        'hero_cta_secondary'        => 'Voir comment on travaille',
        'hero_cta_secondary_href'   => '/a-propos',
        'intro_tension_title'       => 'Pourquoi l’IA reste au stade du POC au lieu de sécuriser vos gains',
        'intro_today_label'         => 'Aujourd’hui',
        'intro_tomorrow_label'      => 'Demain',
        'intro_problems'            => [
            'Expérimentations décorrélées des données et des processus réels.',
            'Risques conformité / RGPD / traçabilité sous-estimés en production.',
            'Outils IA empilés sans propriétaire métier ni critères de succès.',
            'Effet démo : enthousiasme court, peu de valeur durable mesurée.',
        ],
        'intro_solutions'           => [
            'Diagnostic et feuille de route avant tout investissement massif.',
            'Cas d’usage priorisés, intégration SI et reprise sur erreur.',
            'Gouvernance données, modèles et conformité intégrées au design.',
            'Formation et adoption pour que l’IA serve le système, pas l’inverse.',
        ],
        'highlights'                => [
            'Du diagnostic à la prod',
            'Gouvernance & conformité',
            'Valeur métier mesurable',
        ],
        'categories'                => [
            [
                'href'     => '/intelligence-artificielle/agents-ia',
                'title'    => 'Agents IA sur mesure',
                'text'     => 'Agents vocaux, IA agentique, RH, commercial et disponibilité 24/7.',
                'seo_line' => 'Agents IA métiers : conception, garde-fous et mise en production avec traçabilité.',
                'keywords' => ['agent IA entreprise', 'IA conversationnelle', 'IA agentique', 'chatbot métier'],
            ],
            [
                'href'     => '/intelligence-artificielle/automatisation-ia',
                'title'    => 'Automatisation par l’IA',
                'text'     => 'Processus métiers, n8n, Make, orchestration et fiabilité.',
                'seo_line' => 'Automatisation IA et orchestration : fiabilité, reprise sur erreur et supervision des flux.',
                'keywords' => ['automatisation IA', 'orchestration n8n', 'Make entreprise', 'workflow IA'],
            ],
            [
                'href'     => '/intelligence-artificielle/formation-ia',
                'title'    => 'Formation à l’IA',
                'text'     => 'CPF, IA générative, marketing, dirigeants et montée en compétences.',
                'seo_line' => 'Formation IA pour équipes et dirigeants : usages utiles, risques et bonnes pratiques.',
                'keywords' => ['formation IA CPF', 'IA générative entreprise', 'formation ChatGPT', 'montée en compétences IA'],
            ],
            [
                'href'     => '/intelligence-artificielle/ia-entreprise',
                'title'    => 'Stratégie & audit IA',
                'text'     => 'Stratégie IA en entreprise, audits, solutions et impact.',
                'seo_line' => 'Stratégie et audit IA : feuille de route, conformité données et ROI attendu.',
                'keywords' => ['stratégie IA entreprise', 'audit IA', 'gouvernance données IA', 'RGPD IA'],
            ],
        ],
    ],
];
