<?php

/**
 * Routes générées depuis complianz_pages_service.csv
 * Inclure via : require __DIR__ . '/routes_csv.php';
 */

use App\Controllers\PageController;

$pages = [
    '/audit-conformite/conformite-rgpd' => 'Mise en conformité RGPD',
    '/audit-conformite/conformite-rgpd/audit-rgpd' => 'Audit RGPD',
    '/audit-conformite/conformite-rgpd/dpo-externalise' => 'DPO externalisé',
    '/audit-conformite/conformite-rgpd/registre-traitements' => 'Registre des traitements',
    '/audit-conformite/conformite-rgpd/politique-confidentialite' => 'Politique de confidentialité',
    '/audit-conformite/certifications-iso' => 'Accompagnement certifications ISO',
    '/audit-conformite/certifications-iso/iso-9001' => 'Certification ISO 9001',
    '/audit-conformite/certifications-iso/iso-27001' => 'Certification ISO 27001',
    '/audit-conformite/certifications-iso/smq' => 'Mise en place SMQ',
    '/audit-conformite/certifications-iso/audit-qualite' => 'Audit qualité interne',
    '/audit-conformite/cybersecurite' => 'Audit & sécurisation cybersécurité',
    '/audit-conformite/cybersecurite/audit-cybersecurite' => 'Audit de cybersécurité',
    '/audit-conformite/cybersecurite/pentest' => 'Test d\'intrusion (pentest)',
    '/audit-conformite/cybersecurite/politique-securite' => 'Politique de sécurité informatique',
    '/audit-conformite/cybersecurite/protection-cyberattaques' => 'Protection contre les cyberattaques',
    '/audit-conformite/rse' => 'Accompagnement démarche RSE',
    '/audit-conformite/rse/strategie-rse' => 'Stratégie RSE',
    '/audit-conformite/rse/bilan-carbone-reporting' => 'Bilan carbone & reporting ESG',
    '/audit-conformite/rse/label-certification-rse' => 'Label & certification RSE',
    '/audit-conformite/audit-conseil' => 'Audit global & Conseil stratégique',
    '/audit-conformite/audit-conseil/audit-organisationnel' => 'Audit organisationnel',
    '/audit-conformite/audit-conseil/structuration-gouvernance' => 'Structuration & gouvernance',
    '/audit-conformite/audit-conseil/creation-entreprise' => 'Accompagnement à la création d\'entreprise',
    '/solutions-developpement/creation-site-web' => 'Création de sites web',
    '/solutions-developpement/creation-site-web/site-vitrine' => 'Site vitrine professionnel',
    '/solutions-developpement/creation-site-web/site-ecommerce' => 'Site e-commerce',
    '/solutions-developpement/creation-site-web/refonte-site' => 'Refonte de site web',
    '/solutions-developpement/creation-site-web/landing-pages' => 'Landing pages & pages de conversion',
    '/solutions-developpement/creation-site-web/wordpress-cms' => 'Intégration WordPress & CMS',
    '/solutions-developpement/erp-crm' => 'Création ERP & CRM sur mesure',
    '/solutions-developpement/erp-crm/crm-sur-mesure' => 'CRM sur mesure',
    '/solutions-developpement/erp-crm/erp-sur-mesure' => 'ERP sur mesure',
    '/solutions-developpement/erp-crm/gestion-commerciale' => 'Logiciel de gestion commerciale',
    '/solutions-developpement/erp-crm/integration-odoo' => 'Intégration Odoo & ERP existants',
    '/solutions-developpement/developpement-logiciel' => 'Développement logiciel & SaaS sur mesure',
    '/solutions-developpement/developpement-logiciel/application-metier' => 'Application métier sur mesure',
    '/solutions-developpement/developpement-logiciel/saas' => 'Développement SaaS',
    '/solutions-developpement/developpement-logiciel/automatisation-api' => 'Automatisation & API',
    '/performance-digitale/seo' => 'Référencement naturel (SEO)',
    '/performance-digitale/seo/audit-seo' => 'Audit SEO',
    '/performance-digitale/seo/seo-local' => 'SEO local',
    '/performance-digitale/seo/netlinking' => 'Netlinking & stratégie de liens',
    '/performance-digitale/seo/seo-technique' => 'SEO technique',
    '/performance-digitale/seo/redaction-seo' => 'Rédaction SEO & stratégie de contenu',
    '/performance-digitale/tunnel-de-vente' => 'Optimisation tunnel de conversion',
    '/performance-digitale/tunnel-de-vente/creation-tunnel' => 'Création de tunnels de vente',
    '/performance-digitale/tunnel-de-vente/cro' => 'CRO — Optimisation du taux de conversion',
    '/performance-digitale/strategie-digitale' => 'Stratégie digitale globale',
    '/performance-digitale/strategie-digitale/marketing-digital' => 'Marketing digital & réseaux sociaux',
    '/performance-digitale/strategie-digitale/email-marketing' => 'Email marketing & automation',
    '/performance-digitale/strategie-digitale/publicite-digitale' => 'Publicité digitale (SEA & Social Ads)',
    '/performance-digitale/pilotage-commercial' => 'Pilotage commercial & KPI',
    '/performance-digitale/pilotage-commercial/tableau-de-bord' => 'Tableau de bord commercial',
    '/performance-digitale/pilotage-commercial/analyse-performance' => 'Analyse de performance & data',
    '/support-maintenance/maintenance' => 'Maintenance & Support technique',
    '/support-maintenance/maintenance/maintenance-corrective-evolutive' => 'Maintenance corrective & évolutive',
    '/support-maintenance/maintenance/debug' => 'Debug & résolution de bugs',
    '/support-maintenance/maintenance/support-technique' => 'Support technique externalisé',
    '/support-maintenance/infogerance' => 'Infogérance & Hébergement',
    '/support-maintenance/infogerance/infogerance-complete' => 'Infogérance complète',
    '/support-maintenance/infogerance/hebergement-serveur' => 'Hébergement serveur dédié & VPS',
    '/support-maintenance/infogerance/cloud-infrastructure' => 'Cloud & infrastructure managée',
    '/intelligence-artificielle/automatisation-ia' => 'Automatisation des processus par l\'IA',
    '/intelligence-artificielle/automatisation-ia/automatisation-des-processus-metiers' => 'Automatisation des processus métiers',
    '/intelligence-artificielle/automatisation-ia/apprendre-l-automatisation-ia' => 'Apprendre l\'automatisation IA',
    '/intelligence-artificielle/automatisation-ia/agence-specialisee-en-automatisation-ia' => 'Agence spécialisée en automatisation IA',
    '/intelligence-artificielle/automatisation-ia/comment-automatiser-une-tache-avec-l-ia' => 'Comment automatiser une tâche avec l\'IA',
    '/intelligence-artificielle/automatisation-ia/automatisation-ia-avec-n8n' => 'Automatisation IA avec n8n',
    '/intelligence-artificielle/automatisation-ia/formation-a-l-automatisation-ia' => 'Formation à l\'automatisation IA',
    '/intelligence-artificielle/agents-ia' => 'Agents IA sur mesure',
    '/intelligence-artificielle/agents-ia/agent-vocal-ia-pour-entreprise' => 'Agent vocal IA pour entreprise',
    '/intelligence-artificielle/agents-ia/ia-agentique' => 'IA agentique : définition et applications',
    '/intelligence-artificielle/agents-ia/agent-ia-disponible-24h-24-pour-pme' => 'Agent IA disponible 24h/24 pour PME',
    '/intelligence-artificielle/agents-ia/agent-ia-pour-les-ressources-humaines' => 'Agent IA pour les ressources humaines',
    '/intelligence-artificielle/agents-ia/agent-ia-pour-la-performance-commerciale' => 'Agent IA pour la performance commerciale',
    '/intelligence-artificielle/agents-ia/outils-de-developpement-d-agents-ia' => 'Outils de développement d\'agents IA',
    '/intelligence-artificielle/formation-ia' => 'Formation à l\'Intelligence Artificielle',
    '/intelligence-artificielle/formation-ia/formation-ia-eligible-cpf' => 'Formation IA éligible CPF',
    '/intelligence-artificielle/formation-ia/formation-ia-gratuite-en-ligne' => 'Formation IA gratuite en ligne',
    '/intelligence-artificielle/formation-ia/formation-ia-generative' => 'Formation IA générative',
    '/intelligence-artificielle/formation-ia/formation-ia-pour-le-marketing' => 'Formation IA pour le marketing',
    '/intelligence-artificielle/formation-ia/formation-ia-pour-responsable-qse' => 'Formation IA pour responsable QSE',
    '/intelligence-artificielle/formation-ia/formation-ia-pour-dirigeants-d-entreprise' => 'Formation IA pour dirigeants d\'entreprise',
    '/intelligence-artificielle/outils-ia' => 'Outils IA pour entreprises',
    '/intelligence-artificielle/outils-ia/outils-ia-pour-le-community-management' => 'Outils IA pour le community management',
    '/intelligence-artificielle/outils-ia/outils-ia-pour-le-marketing-digital' => 'Outils IA pour le marketing digital',
    '/intelligence-artificielle/outils-ia/outils-ia-pour-la-comptabilite' => 'Outils IA pour la comptabilité',
    '/intelligence-artificielle/outils-ia/outils-ia-pour-le-seo' => 'Outils IA pour le SEO',
    '/intelligence-artificielle/outils-ia/outils-ia-d-automatisation-de-taches' => 'Outils IA d\'automatisation de tâches',
    '/intelligence-artificielle/outils-ia/integration-ia-dans-l-entreprise' => 'Intégration IA dans l\'entreprise',
    '/intelligence-artificielle/ia-entreprise' => 'Stratégie IA pour les entreprises',
    '/intelligence-artificielle/ia-entreprise/ia-generative-en-entreprise' => 'IA générative en entreprise',
    '/intelligence-artificielle/ia-entreprise/conformite-ia-et-ai-act-pour-les-entreprises' => 'Conformité IA et AI Act pour les entreprises',
    '/intelligence-artificielle/ia-entreprise/plateforme-chatbot-ia-d-entreprise' => 'Plateforme chatbot IA d\'entreprise',
    '/intelligence-artificielle/ia-entreprise/ia-pour-les-solutions-rh' => 'IA pour les solutions RH',
    '/intelligence-artificielle/ia-entreprise/choisir-un-nom-d-entreprise-ia' => 'Choisir un nom d\'entreprise IA',
    '/intelligence-artificielle/ia-entreprise/gouvernance-des-donnees-et-ia' => 'Gouvernance des données et IA',
    '/intelligence-artificielle/solutions-ia' => 'Solutions IA sur mesure',
    '/intelligence-artificielle/solutions-ia/conseil-en-solutions-ia' => 'Conseil en solutions IA',
    '/intelligence-artificielle/solutions-ia/solutions-ia-pour-les-telecoms' => 'Solutions IA pour les télécoms',
    '/intelligence-artificielle/solutions-ia/solutions-ia-de-gouvernance-des-donnees' => 'Solutions IA de gouvernance des données',
    '/intelligence-artificielle/solutions-ia/developpement-ia-sur-mesure' => 'Développement IA sur mesure',
    '/intelligence-artificielle/audit-ia' => 'Audit IA et évaluation des systèmes',
    '/intelligence-artificielle/audit-ia/audit-ia-et-seo' => 'Audit IA et SEO — Visibilité dans les moteurs IA',
    '/intelligence-artificielle/audit-ia/audit-geo' => 'Audit GEO — Generative Engine Optimization',
    '/intelligence-artificielle/audit-ia/audit-des-processus-metiers-ia' => 'Audit des processus métiers IA',
    '/intelligence-artificielle/audit-ia/audit-technique-des-systemes-ia' => 'Audit technique des systèmes IA',
    '/intelligence-artificielle/impact-ia' => 'Impact de l\'IA sur l\'environnement et l\'emploi',
    '/intelligence-artificielle/impact-ia/impact-environnemental-de-l-ia' => 'Impact environnemental de l\'IA',
    '/intelligence-artificielle/impact-ia/impact-de-l-ia-sur-l-emploi' => 'Impact de l\'IA sur l\'emploi',
    '/intelligence-artificielle/impact-ia/empreinte-ecologique-de-l-ia' => 'Empreinte écologique de l\'IA',
    '/intelligence-artificielle/impact-ia/ia-responsable-et-ethique-en-entreprise' => 'IA responsable et éthique en entreprise',
];

foreach ($pages as $path => $title) {
    $router->get($path, static function ($req, $p) use ($title): void {
        (new PageController())->show($req, array_merge($p, ['title' => $title]));
    });
}
