<?php

/**
 * Documentation Wiki — structure scalable (nav, hub, pages).
 * Contenu : métadonnées ici ; corps riche dans templates/wiki/bodies/*.twig
 */
return [
    'nav' => [
        [
            'id'    => 'demarrer',
            'label' => 'Démarrer',
            'icon'  => 'rocket',
            'pages' => [
                ['slug' => 'introduction', 'label' => 'Introduction'],
                ['slug' => 'parcours-par-profil', 'label' => 'Parcours par profil'],
            ],
        ],
        [
            'id'    => 'systeme',
            'label' => 'Architecture & système',
            'icon'  => 'layers',
            'pages' => [
                ['slug' => 'vue-d-ensemble', 'label' => 'Vue d’ensemble'],
                ['slug' => 'flux-et-donnees', 'label' => 'Flux & données'],
            ],
        ],
        [
            'id'    => 'integration',
            'label' => 'Intégration & API',
            'icon'  => 'code',
            'pages' => [
                ['slug' => 'conventions-api', 'label' => 'Conventions API'],
                ['slug' => 'exemple-integration', 'label' => 'Exemple d’intégration'],
            ],
        ],
        [
            'id'    => 'support',
            'label' => 'FAQ & support',
            'icon'  => 'help',
            'pages' => [
                ['slug' => 'faq', 'label' => 'FAQ & dépannage'],
            ],
        ],
    ],

    'hub_categories' => [
        [
            'id'          => 'demarrer',
            'title'       => 'Démarrer vite',
            'description' => 'Cartographier le wiki, choisir son parcours et comprendre les grands principes.',
            'accent'      => 'blue',
            'links'       => [
                ['slug' => 'introduction', 'label' => 'Introduction — périmètre & objectifs'],
                ['slug' => 'parcours-par-profil', 'label' => 'Parcours par profil (dev, métier, partenaire)'],
            ],
        ],
        [
            'id'          => 'systeme',
            'title'       => 'Comprendre le système',
            'description' => 'Modules, flux, dépendances : la colonne vertébrale pour ne pas se perdre.',
            'accent'      => 'green',
            'links'       => [
                ['slug' => 'vue-d-ensemble', 'label' => 'Vue d’ensemble'],
                ['slug' => 'flux-et-donnees', 'label' => 'Flux & cycle de vie des données'],
            ],
        ],
        [
            'id'          => 'integration',
            'title'       => 'Intégrer & automatiser',
            'description' => 'Conventions techniques, payloads, erreurs et exemples prêts à l’emploi.',
            'accent'      => 'amber',
            'links'       => [
                ['slug' => 'conventions-api', 'label' => 'Conventions API'],
                ['slug' => 'exemple-integration', 'label' => 'Cas d’usage pas à pas'],
            ],
        ],
        [
            'id'          => 'support',
            'title'       => 'Débloquer & contribuer',
            'description' => 'Questions fréquentes, pièges connus, pistes avant le support humain.',
            'accent'      => 'slate',
            'links'       => [
                ['slug' => 'faq', 'label' => 'FAQ & dépannage'],
            ],
        ],
    ],

    'pages' => [
        'introduction' => [
            'nav_section' => 'demarrer',
            'title'       => 'Introduction — Wiki Complianz',
            'h1'          => 'Introduction au documentation Complianz',
            'description' => 'Périmètre du wiki, publics visés et comment naviguer efficacement.',
            'tags'        => ['Fondations', 'Navigation', 'Équipe'],
            'breadcrumbs' => [
                ['label' => 'Wiki', 'href' => '/wiki'],
                ['label' => 'Démarrer', 'href' => null],
                ['label' => 'Introduction', 'href' => null],
            ],
            'ctas' => [
                ['href' => '/contact', 'label' => 'Tester une demande', 'variant' => 'primary'],
                ['href' => '/hub', 'label' => 'Voir le Hub d’innovation', 'variant' => 'outline'],
                ['href' => 'https://github.com/', 'label' => 'Voir un exemple de repo', 'variant' => 'ghost', 'external' => true],
            ],
            'updated'  => '2026-05-02',
            'version'  => '1.0',
            'author'   => 'Équipe Complianz',
            'intro'    => [
                'summary'    => 'Ce wiki centralise la documentation produit, les guides d’intégration et les réponses aux questions récurrentes. Il est conçu pour être parcouru par tranches (profil, sujet, tâche) ou en lecture linéaire.',
                'objective'  => 'Vous donner une vision claire du système et des points d’entrée actionnables sans multiplier les allers-retours avec le support.',
                'audience'   => 'Développeurs, chefs de projet, partenaires intégrateurs et clients techniques.',
                'prereq'     => 'Aucun prérequis pour cette page ; les pages « API » supposent des bases HTTP/JSON.',
            ],
            'toc' => [
                ['id' => 'contexte', 'label' => 'Contexte & objectifs'],
                ['id' => 'organisation', 'label' => 'Organisation de l’information'],
                [
                    'id'       => 'principes',
                    'label'    => 'Principes d’accessibilité',
                    'children' => [
                        ['id' => 'principes-structure', 'label' => 'Structure & repères'],
                        ['id' => 'principes-recherche', 'label' => 'Recherche & filtres'],
                    ],
                ],
                ['id' => 'exemples', 'label' => 'Exemples rapides'],
                ['id' => 'faq-intro', 'label' => 'FAQ courte'],
            ],
            'prev'    => null,
            'next'    => ['slug' => 'parcours-par-profil', 'label' => 'Parcours par profil'],
            'related' => [
                ['slug' => 'vue-d-ensemble', 'label' => 'Vue d’ensemble du système'],
                ['slug' => 'faq', 'label' => 'FAQ'],
            ],
            'body' => 'wiki/bodies/introduction.twig',
        ],
        'parcours-par-profil' => [
            'nav_section' => 'demarrer',
            'title'       => 'Parcours par profil — Wiki',
            'h1'          => 'Choisir son parcours : dev, métier ou partenaire',
            'description' => 'Quelles sections lire en premier selon votre rôle.',
            'tags'        => ['Parcours', 'IA informationnelle'],
            'breadcrumbs' => [
                ['label' => 'Wiki', 'href' => '/wiki'],
                ['label' => 'Démarrer', 'href' => null],
                ['label' => 'Parcours par profil', 'href' => null],
            ],
            'ctas' => [
                ['href' => '/wiki/introduction', 'label' => 'Revenir à l’intro', 'variant' => 'outline'],
                ['href' => '/contact', 'label' => 'Parler à l’équipe', 'variant' => 'primary'],
            ],
            'updated' => '2026-05-02',
            'version' => '1.0',
            'author'  => 'Équipe Complianz',
            'intro'   => [
                'summary'   => 'La même documentation peut servir plusieurs publics : cette page propose des itinéraires de lecture courts pour aller droit au but.',
                'objective' => 'Réduire le bruit cognitif et orienter chaque profil vers 3 à 5 pages utiles.',
                'audience'  => 'Tous profils — commencez par votre colonne.',
                'prereq'    => 'Aucun.',
            ],
            'toc' => [
                ['id' => 'profil-dev', 'label' => 'Profil développeur'],
                ['id' => 'profil-metier', 'label' => 'Profil métier / produit'],
                ['id' => 'profil-partenaire', 'label' => 'Profil partenaire'],
            ],
            'prev'    => ['slug' => 'introduction', 'label' => 'Introduction'],
            'next'    => ['slug' => 'vue-d-ensemble', 'label' => 'Vue d’ensemble'],
            'related' => [['slug' => 'conventions-api', 'label' => 'Conventions API']],
            'body'    => 'wiki/bodies/parcours-par-profil.twig',
        ],
        'vue-d-ensemble' => [
            'nav_section' => 'systeme',
            'title'       => 'Vue d’ensemble — Wiki',
            'h1'          => 'Vue d’ensemble du système Complianz',
            'description' => 'Cartographie logique : briques, responsabilités et flux.',
            'tags'        => ['Architecture', 'Système'],
            'breadcrumbs' => [
                ['label' => 'Wiki', 'href' => '/wiki'],
                ['label' => 'Architecture & système', 'href' => null],
                ['label' => 'Vue d’ensemble', 'href' => null],
            ],
            'ctas' => [
                ['href' => '/wiki/flux-et-donnees', 'label' => 'Creuser les flux', 'variant' => 'primary'],
            ],
            'updated' => '2026-05-02',
            'version' => '1.0',
            'author'  => 'Équipe Complianz',
            'intro'   => [
                'summary'   => 'Schéma mental du produit : ce qui est côté client, côté serveur et côté tiers.',
                'objective' => 'Donner une carte mentale avant d’entrer dans le détail des API.',
                'audience'  => 'Architectes, tech leads, intégrateurs.',
                'prereq'    => 'Notions générales d’architecture web.',
            ],
            'toc' => [
                ['id' => 'couches', 'label' => 'Couches applicatives'],
                ['id' => 'diagramme', 'label' => 'Diagramme simplifié'],
            ],
            'prev'    => ['slug' => 'parcours-par-profil', 'label' => 'Parcours par profil'],
            'next'    => ['slug' => 'flux-et-donnees', 'label' => 'Flux & données'],
            'related' => [['slug' => 'introduction', 'label' => 'Introduction']],
            'body'    => 'wiki/bodies/vue-d-ensemble.twig',
        ],
        'flux-et-donnees' => [
            'nav_section' => 'systeme',
            'title'       => 'Flux & données — Wiki',
            'h1'          => 'Flux & cycle de vie des données',
            'description' => 'Entrées, traitements, stockages et exports.',
            'tags'        => ['Données', 'RGPD'],
            'breadcrumbs' => [
                ['label' => 'Wiki', 'href' => '/wiki'],
                ['label' => 'Architecture & système', 'href' => null],
                ['label' => 'Flux & données', 'href' => null],
            ],
            'ctas'      => [['href' => '/audit-conformite/conformite-rgpd/politique-confidentialite', 'label' => 'Politique de confidentialité', 'variant' => 'outline']],
            'updated'   => '2026-05-02',
            'version'   => '1.0',
            'author'    => 'Équipe Complianz',
            'intro'     => [
                'summary' => 'Vue des flux entre interfaces, API et stockages, avec points d’attention conformité.',
                'objective' => 'Identifier où les données naissent, où elles transitent et où elles sont persistées.',
                'audience' => 'DPO techniques, développeurs, auditeurs.',
                'prereq' => 'Lecture de la vue d’ensemble recommandée.',
            ],
            'toc'     => [['id' => 'cycle', 'label' => 'Cycle de vie'], ['id' => 'exports', 'label' => 'Exports & journaux']],
            'prev'    => ['slug' => 'vue-d-ensemble', 'label' => 'Vue d’ensemble'],
            'next'    => ['slug' => 'conventions-api', 'label' => 'Conventions API'],
            'related' => [],
            'body'    => 'wiki/bodies/flux-et-donnees.twig',
        ],
        'conventions-api' => [
            'nav_section' => 'integration',
            'title'       => 'Conventions API — Wiki',
            'h1'          => 'Conventions communes des API',
            'description' => 'Versioning, erreurs, pagination, idempotence.',
            'tags'        => ['API', 'REST', 'JSON'],
            'breadcrumbs' => [
                ['label' => 'Wiki', 'href' => '/wiki'],
                ['label' => 'Intégration & API', 'href' => null],
                ['label' => 'Conventions API', 'href' => null],
            ],
            'ctas' => [['href' => '/wiki/exemple-integration', 'label' => 'Voir un exemple', 'variant' => 'primary']],
            'updated' => '2026-05-02',
            'version' => '1.0',
            'author'  => 'Équipe Complianz',
            'intro'   => [
                'summary' => 'Contrat implicite des endpoints exposés par la plateforme et les intégrations tierces.',
                'objective' => 'Aligner les intégrations sur des patterns prévisibles (codes HTTP, enveloppes JSON).',
                'audience' => 'Développeurs backend & intégrateurs.',
                'prereq' => 'REST, JSON, codes HTTP.',
            ],
            'toc' => [['id' => 'versioning', 'label' => 'Versioning'], ['id' => 'erreurs', 'label' => 'Erreurs'], ['id' => 'table-endpoints', 'label' => 'Tableau d’endpoints']],
            'prev'    => ['slug' => 'flux-et-donnees', 'label' => 'Flux & données'],
            'next'    => ['slug' => 'exemple-integration', 'label' => 'Exemple d’intégration'],
            'related' => [['slug' => 'faq', 'label' => 'FAQ']],
            'body'    => 'wiki/bodies/conventions-api.twig',
        ],
        'exemple-integration' => [
            'nav_section' => 'integration',
            'title'       => 'Exemple d’intégration — Wiki',
            'h1'          => 'Cas d’usage : synchroniser un formulaire métier',
            'description' => 'Étapes, payload et vérifications.',
            'tags'        => ['Tutoriel', 'Exemple'],
            'breadcrumbs' => [
                ['label' => 'Wiki', 'href' => '/wiki'],
                ['label' => 'Intégration & API', 'href' => null],
                ['label' => 'Exemple d’intégration', 'href' => null],
            ],
            'ctas' => [['href' => '/contact', 'label' => 'Demander une revue d’archi', 'variant' => 'primary']],
            'updated' => '2026-05-02',
            'version' => '1.0',
            'author'  => 'Équipe Complianz',
            'intro'   => [
                'summary' => 'Un scénario bout-en-bout, du front office à la persistance, avec points de contrôle.',
                'objective' => 'Donner un modèle reproductible pour vos propres flux.',
                'audience' => 'Développeurs full-stack.',
                'prereq' => 'Conventions API lues au préalable.',
            ],
            'toc' => [['id' => 'etapes', 'label' => 'Étapes'], ['id' => 'checklist', 'label' => 'Checklist go-live']],
            'prev'    => ['slug' => 'conventions-api', 'label' => 'Conventions API'],
            'next'    => ['slug' => 'faq', 'label' => 'FAQ'],
            'related' => [],
            'body'    => 'wiki/bodies/exemple-integration.twig',
        ],
        'faq' => [
            'nav_section' => 'support',
            'title'       => 'FAQ & dépannage — Wiki',
            'h1'          => 'FAQ — problèmes fréquents',
            'description' => 'Résolution rapide des erreurs et questions récurrentes.',
            'tags'        => ['Support', 'Debug'],
            'breadcrumbs' => [
                ['label' => 'Wiki', 'href' => '/wiki'],
                ['label' => 'FAQ & support', 'href' => null],
                ['label' => 'FAQ', 'href' => null],
            ],
            'ctas' => [['href' => '/contact', 'label' => 'Ouvrir un ticket / contact', 'variant' => 'primary']],
            'updated' => '2026-05-02',
            'version' => '1.0',
            'author'  => 'Équipe Complianz',
            'intro'   => [
                'summary' => 'Synthèse des symptômes les plus signalés et des premiers réflexes à adopter.',
                'objective' => 'Réduire le temps avant escalade humaine.',
                'audience' => 'Tous profils.',
                'prereq' => 'Aucun.',
            ],
            'toc' => [['id' => 'auth', 'label' => 'Authentification'], ['id' => 'quota', 'label' => 'Quotas & limites']],
            'prev'    => ['slug' => 'exemple-integration', 'label' => 'Exemple d’intégration'],
            'next'    => null,
            'related' => [['slug' => 'introduction', 'label' => 'Introduction']],
            'body'    => 'wiki/bodies/faq.twig',
        ],
    ],
];
